### ISSUE TITLE
None of these files exist Single date picker

### ISSUE THREAD

**Issue by mschief148** [web-ridge/react-native-paper-dates#101]
I got a Syntax Error with the error showing in the image. Saying none of these files exist on android emulator.  I followed the Android caveats and it didn't work.

This is my implementation code: 

```
export const DateInput = ({ mode, label }: DateInputProps) => {
  const [opened, setOpened] = React.useState(false);

  const onDismiss = React.useCallback(() => {
    setOpened(false);
  }, [setOpened]);

  return (
    <>
      <TextInput mode={mode} label={label}
        right={<TextInput.Icon color="rgba(0,0,0,0.6)" name="calendar" forceTextInputFocus={false}
          onPress={() => setOpened(true)}
        />}
      />
      <DatePickerModal mode="single" visible={opened} onConfirm={ () => console.log('confirmed')} onDismiss={onDismiss}/>
    </>
  );
};
```

![image](https://user-images.githubusercontent.com/28127669/132146316-0ce93e2d-aec4-42ca-aa4b-0a1e16639c96.png)

Any help is appreciated. Thanks

**Comment by RichardLindhout** [comment]
Did you install via npm or via github directly?

**Comment by RichardLindhout** [comment]
DatePickerInput is added in the library itself!
