### ISSUE TITLE
well i had an issue in your other package too and this one is lagging while loading the calendar

### ISSUE THREAD

**Issue by srivastavaanurag79** [web-ridge/react-native-paper-dates#102]
![f9755e05-ea73-4b13-9e46-540db9c2539f (1)](https://user-images.githubusercontent.com/24560090/132682298-5153dcec-0776-4283-8c72-a19698f33ab6.gif)

Ignore the black screen focus on the calendar slow load. I don't know what I did wrong? and it's lagging on my physical device as well

**Comment by RichardLindhout** [comment]
It's React Native, it's just slow on low-end devices, I hope Fabric (will hopefully be available this year) will improve performance, I also suspect some low level components from react-native-paper to be slow, but I have done all possible optimizations on this.

If you need to have a faster date picker use the native picker which are available in other packages and they render the native calendar.

**Comment by RichardLindhout** [comment]
Have you enabled Hermes?

**Comment by srivastavaanurag79** [comment]
Hermes is enabled in my project, and I tested it on pixel 3 and a phone with a Snapdragon 732G processor with 6gb ram  and an iPhone 11 pro of a colleague btw nevermind I have already switched to another package. I raised this ticket to let you know that the package doesn't work as it says, i.e. to be smooth.
