### ISSUE TITLE
UIViewControllerBasedStatusBarAppearance Info.plist set to NO

### ISSUE THREAD

**Issue by aretesoftware** [web-ridge/react-native-paper-dates#112]
Are we forced to set this to NO?  I'd like to be able to set this to YES.

![Screen Shot 2021-10-26 at 7 09 57 PM](https://user-images.githubusercontent.com/31421715/138974143-0260b7bb-0c86-41e8-b215-9cf9855cd3f0.png)

**Comment by poy004id** [comment]
Can you explain it? 
I am searching on the docs, there is no prop disableStatusBar.  Neither in react native StatusBar
 

> disableStatusBar={true} seems to work well...
