### ISSUE TITLE
Make it possible to start the week on monday

### ISSUE THREAD

**Issue by rathierry** [web-ridge/react-native-paper-dates#116]
How to do it with version 0.4.6 ?

**Comment by rathierry** [comment]
@RichardLindhout, is this already possible with version 0.4.6 ?!!!
Thanks

**Comment by RichardLindhout** [comment]
Nope, still not possible, I think it's hard + I don't have time to implement it a.t.m.

**Comment by RichardLindhout** [comment]
I would accept PR's which implement this feature ofcourse!

**Comment by RichardLindhout** [comment]
@rathierry duplicate of https://github.com/web-ridge/react-native-paper-dates/issues/20

**Comment by RichardLindhout** [comment]
Locked please continue discussion in: https://github.com/web-ridge/react-native-paper-dates/issues/20
