### ISSUE TITLE
Uppercase attribute exposure

### ISSUE THREAD

**Issue by iM-GeeKy** [web-ridge/react-native-paper-dates#119]
@RichardLindhout - Would there be any opposition to exposing a `uppercase` property similar to `react-native-papers` [ button](https://callstack.github.io/react-native-paper/button.html#uppercase)? If so, I've submitted a [PR](https://github.com/web-ridge/react-native-paper-dates/pull/120).

**Comment by RichardLindhout** [comment]
Super cool!

**Comment by iM-GeeKy** [comment]
> Super cool!

Btw, It looks like the type for `uppercase` is somehow being stripped out so TypeScript is complaining since it does not recognize it.

**Comment by RichardLindhout** [comment]
Released!
