### ISSUE TITLE
Date picker modal not showing in android

### ISSUE THREAD

**Issue by premdasvm** [web-ridge/react-native-paper-dates#121]
Hi, I was trying to implement the date picker onto my application, but the date picker modal isn't showing up on my android version, on IOS it works like charm, can someone help me out here.?

```
<DatePickerInput
    locale="en"
    label="Valid till date"
    value={inputDate}
    onChange={d => {
      console.log(d)
    }}
   inputMode="start"
   mode="outlined"
   style={{width: '90%', marginTop: '2.5%'}}
/>
```

![video_2021-11-29_16-48-15](https://user-images.githubusercontent.com/14838550/143859345-7b8d8368-e048-421a-ba4f-0920ab685cd8.gif)

**Comment by premdasvm** [comment]
Removing `mode="outlined"` seem to fixed it.

**Comment by RichardLindhout** [comment]
Hmm I think it should work with outlined but I only tested it on the web & iOS and not on Android yet

**Comment by professionally** [comment]
Hi.
Had the same problem.
I fixed it by adding a zindex to the style.calendarButton in line 130 in src/Date/DatePickerInput.tsx.
`const styles = StyleSheet.create({
  root: {
    minWidth: 150,
    flexDirection: 'row',
    position: 'relative',
    alignItems: 'center',
    flexGrow: 1,
    alignSelf: 'flex-start'
  },
  input: {
    flexGrow: 1,
  },
  calendarButton: { position: 'absolute', right: 0, zIndex:1000 },
})
export default React.forwardRef(DatePickerInput)
`

**Comment by RichardLindhout** [comment]
This should be fixed now! Thanks @professionally
