### ISSUE TITLE
Manual date input is expecting the date to be in MM/1/YYYY format.

### ISSUE THREAD

**Issue by napzZztar** [web-ridge/react-native-paper-dates#123]
I think the problem I'm facing might be related to [Issue#63](https://github.com/web-ridge/react-native-paper-dates/issues/63).

The problem is, when I click on manual date edit button the format shown here is `MM/1/YYYY` which doesn't make any sense to me.

Also, if I try to insert a date in `MM/DD/YYYY` format using keyboard, the module automatically inserts a `/`after the third input digit. So, basically if I type `0102` it becomes `01/0/`.

**Comment by RichardLindhout** [comment]
Which versions do you have of React Native? Which locale is configured?

**Comment by RichardLindhout** [comment]
It should work automatically based on locale (Intl API's support this)

**Comment by napzZztar** [comment]
I'm using Expo SDK: 42.0.0 which uses React Native 0.63.

**Comment by varunhhhrahul** [comment]
I am experiencing the same issue, is there any fix yet?

**Comment by RichardLindhout** [comment]
Do you use the formatjs polyfill of the Readme? I think Expo & RN 0.63 has still no Hermes with Intl support unfortunaly :(

**Comment by napzZztar** [comment]
@RichardLindhout , thanks!! This resolved it for me. As, I'm using expo, I had to use `expo-localization` instead of `react-native-localize`.

**Comment by majlindaIsmaili** [comment]
Hello, how can I use only keyboard type TimePicker?!

**Comment by ankitfyntune** [comment]
> @RichardLindhout , thanks!! This resolved it for me. As, I'm using expo, I had to use `expo-localization` instead of `react-native-localize`.

@napzZztar please help, I face same issue.
