### ISSUE TITLE
Conditionally render HelperText in DatePickerInput

### ISSUE THREAD

**Issue by Grijnak** [web-ridge/react-native-paper-dates#124]
HelperText will take up space even when not visible. The recommended fix is to render it conditionally: [react-native-paper/issues/2316](https://github.com/callstack/react-native-paper/issues/2316).

This can lead to weird looking empty spaces and sometimes the HelperText will never be used anyway making it in the way.

![Unused HelperText taking up space](https://user-images.githubusercontent.com/79847695/146999756-329ecb9d-edde-4049-b5e4-818f517cbb2e.png)

**Comment by RichardLindhout** [comment]
You should add the datePicker input in a <View> so it will render below the input (since default flexDirection is column in a View)

**Comment by Grijnak** [comment]
Wrapping the input in a view messes up the row because the helpertext now takes up space below the input. To be clear the issue is that it takes up space, no matter where. Even in it's own row, it will eat space even though nothing is displayed. This is what it looks like with datepickerinput in its own view:

![Screenshot from 2021-12-26 18-52-29](https://user-images.githubusercontent.com/79847695/147416312-ef604592-a31b-4a27-bf55-ff8d88a4d40c.png)

**Comment by RichardLindhout** [comment]
Will be there in next release!
