### ISSUE TITLE
Let user override timezone

### ISSUE THREAD

**Issue by RichardLindhout** [web-ridge/react-native-paper-dates#13]
E.g. could be if the user is in Thailand but he is ordering something in the Netherlands (if your shop is Dutch) Then you would like to show the calendar in that timezone. (?)

**Comment by RichardLindhout** [comment]
If providing a timezone
the date, startDate, endDate should probably be in UTC format

**Comment by Robbilie** [comment]
@RichardLindhout so I am not sure if i should create a seperate issue but this seems be related to not being able to define a timezone. I am in Germany and a date ends up as a utc timestamp with the previous day at 2200 or 2300 depending on summer time. So while the selection is 21., the resulting timestamp is the 21. in my timezone aswell, just not in UTC and it seems the UTC date is what is used for the "SELECT DATE" value…

![Screenshot_20210314-031507](https://user-images.githubusercontent.com/406176/111055221-f4513400-8473-11eb-86a1-6e0a328e1a5b.png)

**Comment by RichardLindhout** [comment]
Please upgrade package, the week should start on saturday.

**Comment by RichardLindhout** [comment]
+ date picker should use timezone of device so are you sure emulator is on the same timezone?

**Comment by Robbilie** [comment]
> Please upgrade package, the week should start on saturday.

the screenshots week starts on saturday, no?

> date picker should use timezone of device so are you sure emulator is on the same timezone?

thats not an emulator, its my phone :) and my phone is set to en-US locale, europe aka CET timezone

**Comment by RichardLindhout** [comment]
I mean it should be Sunday :) 
What happens if you upgrade to a newer version of the package? The datepicker should pick the timezone of the device and return the right time but we had a bug in a previous version with the grid where it would only work in the Netherlands because we used a wrong Day constructor.

https://github.com/web-ridge/react-native-paper-dates/commit/343f9991bd27cae805cb1cf6e759736a88828f23#diff-2559e2b6c4b0f94fc3c597c197336358332aa49d7d15eb54d8229c1067534d6c


Are you also sure you followed the FormatJS steps in the Android caveats section
https://github.com/web-ridge/react-native-paper-dates#android-caveats

And this part:
```
  // https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone
  let RNLocalize = require('react-native-localize');
  if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
    Intl.DateTimeFormat.__setDefaultTimeZone(RNLocalize.getTimeZone());
  }
  ```

**Comment by Robbilie** [comment]
Trying 0.4.0, same picture :/

Great, thats the only part i left out, but it doesnt work, since i am using expo and not native react-native, i get an error about i should link stuff…

```

  // https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone
  if ("__setDefaultTimeZone" in Intl.DateTimeFormat) {
    Intl.DateTimeFormat.__setDefaultTimeZone(
      require("expo-localization").timezone
    );
  }
  ```

that works though, sunday start, correct day, im happy, thanks for your support :)

**Comment by RichardLindhout** [comment]
Yeah thanks you I'll add this to readme

**Comment by ZohaibNaseer786** [comment]
>   // https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone
>   let RNLocalize = require('react-native-localize');
>   if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
>     Intl.DateTimeFormat.__setDefaultTimeZone(RNLocalize.getTimeZone());
>   }

In which file I can add this ?

**Comment by RichardLindhout** [comment]
@ZohaibNaseer786 if you upgrade RN 0.66 and Hermes you won't need this, it will automatically pick the timezone of the device!
