### ISSUE TITLE
Unable to select any hours before noon when TimePickerModal is in 24-hour clock mode

### ISSUE THREAD

**Issue by gbarany** [web-ridge/react-native-paper-dates#132]
I'm unable to select any hour before noon when TimePickerModal is in 24-hour clock mode (e.g. locale is de). 
Only hours after 12 noon can be selected. Issue can be reproduced by changing the **locale** prop to "de" in the Time picker sample code:
```
<TimePickerModal
   visible={visible}
   onDismiss={onDismiss}
   onConfirm={onConfirm}
   hours={12} // default: current hours
   minutes={14} // default: current minutes
   label="Select time" // optional, default 'Select time'
   uppercase={false} // optional, default is true
   cancelLabel="Cancel" // optional, default: 'Cancel'
   confirmLabel="Ok" // optional, default: 'Ok'
   animationType="fade" // optional, default is 'none'
   locale="de"
/>
```

I've tested this with release 0.8.4 on iOS and web.

![Simulator Screen Recording - iPhone 11 - 2022-01-13 at 15 53 06](https://user-images.githubusercontent.com/23645175/149365707-c2e26b21-2bce-4719-9b2c-fe75c38ba692.gif)

**Comment by RichardLindhout** [comment]
@J3j3m could this be related to: https://github.com/web-ridge/react-native-paper-dates/pull/110?

**Comment by RichardLindhout** [comment]
So 23 does not work too or only 00?

**Comment by gbarany** [comment]
> So 23 does not work too or only 00?

I can't pick any hour from the outer circle of the dial (i.e. 1,2,...11)  because the selection automatically jumps on the inner circle. If I try to pick 7 it jumps to 19 automatically.

**Comment by J3j3m** [comment]
Weird, i'll try to check that this week-end

**Comment by RichardLindhout** [comment]
@J3j3m thank you, really nice!

**Comment by gbarany** [comment]
I've tested this behaviour with different different versions. v0.4.6 is the last version where TimePickerModal mode works as expected in 24-hour clock mode. For versions v0.5.0+ only afternoon hours can be picked.

**Comment by gbarany** [comment]
I came up with this patch to fix the issue temporarily:
https://gist.github.com/gbarany/209e1cfab35dd451e2d4133a69511034

**Comment by J3j3m** [comment]
Thanks, i didn't have time this w-e checking this, i'll do that this week.

**Comment by J3j3m** [comment]
I got the point, i'm working on a fix that will not break Am/Pm mode
