### ISSUE TITLE
Select a Range Date, Save, Open again => Error

### ISSUE THREAD

**Issue by alexaalex70** [web-ridge/react-native-paper-dates#137]
HI,

I am selecting a date multiple, than I press save, everything fine, as in example. But when I try to reopen I get this error.

```
TypeError: secondDate.getFullYear is not a function

This error is located at:
    in Calendar (at DatePickerModalContent.tsx:167)
```

If anyone can help, would be great.

Thanks!

**Comment by J3j3m** [comment]
Hi, can 't reproduce the issue. Could you provide sample code ?

**Comment by RichardLindhout** [comment]
@alexaalex70 I think you don't provide a JS Date as value it's not required but if you specify the value it must be a JS Date object instead of something like a string or momentjs date
