### ISSUE TITLE
Unnecessary White Spacing

### ISSUE THREAD

**Issue by samharvey44** [web-ridge/react-native-paper-dates#163]
The 'DatePickerInput' renders with HelperText, which causes empty white space to appear below the element. The 'visible' prop on HelperText does not determine whether it renders - it just either hides or shows it.

It should instead conditionally render the HelperText, so that it only mounts when necessary.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-paper-dates/src/Date/DatePickerInput.tsx b/node_modules/react-native-paper-dates/src/Date/DatePickerInput.tsx
index 541ab98..8fd3998 100644
--- a/node_modules/react-native-paper-dates/src/Date/DatePickerInput.tsx
+++ b/node_modules/react-native-paper-dates/src/Date/DatePickerInput.tsx
@@ -86,9 +86,12 @@ function DatePickerInput(
           />
         ) : null}
       </View>
-      <HelperText type="error" visible={!!error}>
-        {error}
-      </HelperText>
+
+      {!!error && (
+          <HelperText type="error">
+              {error}
+          </HelperText>
+      )}
 
       {withModal ? (
         <DatePickerModal
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by CosminGRG** [comment]
I suppose this is what you are speaking about. The fix above doesn't seem to work for me
![image](https://user-images.githubusercontent.com/50809946/185808586-2009fc92-cb7d-489a-a8f5-9445f21b46c0.png)

**Comment by samharvey44** [comment]
Hi there,

No, I think your issue is a different one.

Mine is related to a small amount of white space caused by a redundant helpertext component being rendered - not the amount of space you are showing.

**Comment by RichardLindhout** [comment]
Ok, I've added this!

**Comment by hfllr** [comment]
I'm experiencing the exact same problem in the most recent version 0.21.7
No way to get rid of the white-spacing
