### ISSUE TITLE
How to change days and month format

### ISSUE THREAD

**Issue by randurd** [web-ridge/react-native-paper-dates#172]
Hello,

Any idea on how to change the days and month format? 
- From juni to june
- From Z M D W D V Z to S M T W TH F S

Version : 0.8.7
Picker:
`  <DatePickerModal
                    locale="en"
                    mode="single"
                    visible={true}
                    onDismiss={() => { }}
                    date={new Date()}
                    onConfirm={(selected) => { }}
                />`

![Screen Shot 2022-06-09 at 12 56 04 PM](https://user-images.githubusercontent.com/107166955/172767693-c6c9c1a8-a260-4e79-8668-1c115c92ae44.png)

**Comment by RichardLindhout** [comment]
Change your locale

**Comment by RichardLindhout** [comment]
locale="en"

**Comment by RichardLindhout** [comment]
Do you use expo / React Native. Do you use polyfills for Intl? 

Possible fix:
Enable Hermes on Android + remove polyfills locale settings will work then probably!

**Comment by randurd** [comment]
> Do you use expo / React Native. Do you use polyfills for Intl?
> 
> Possible fix: Enable Hermes on Android + remove polyfills

Yes I'm using expo / react native and I was able to fixed the issue with your solution. Thanks!

**Comment by timmermansjoy** [comment]
@randurd mark as solved then?

**Comment by javiermojito** [comment]
Hello everyone. It seems that removing the polyfills solves the issue, but how can doing this affects the app?
