### ISSUE TITLE
iOS status bar tap scrolling

### ISSUE THREAD

**Issue by timmermansjoy** [web-ridge/react-native-paper-dates#174]
When using iOS when selecting a date in the `DatePickerModal` it is possible to it the top status bar that makes it so you scroll to the top what makes it so you go to 1925. This looks like a bug and not how it suppose to work?

To replicate this just tap the top of the screen on iOS

![Screenshot 2022-06-29 at 1 49 42 PM](https://user-images.githubusercontent.com/61321383/176429564-39850a42-9f35-4941-bfd6-ef858177cc74.png)

**Comment by RichardLindhout** [comment]
Very strange, PR is welcome (I'm short in time a.t.m)

**Comment by RichardLindhout** [comment]
Fixed in next release!
