### ISSUE TITLE
Web, de locale, analog clock in the morning cannot select noon

### ISSUE THREAD

**Issue by DorianSternVukotic** [web-ridge/react-native-paper-dates#178]
In desktop web, at locale de, in the morning, analog clock shows 00 both in inner and outer circle and it is impossible to select noon.

Reproducible on the demo page of this project

[image](https://ibb.co/2vqngjV)

We fixed on our project by using patch package and turning
Line 37 in src/Time/AnalogClockHours.tsx
`{mode === 'AM' && i + 1 === 12 ? '00' : i + 1}`
into
`{(mode === 'AM' && !!!is24Hour && i + 1 === 12) ? '00' : i + 1}`

**Comment by RichardLindhout** [comment]
Ok I added this, thanks for your solution :)
