### ISSUE TITLE
Support for Arabic/Persian numbers in Calendar as day names + custom days per month / leapyear

### ISSUE THREAD

**Issue by RichardLindhout** [web-ridge/react-native-paper-dates#18]
DoD:
- Uses native Javascript api's as much as possible Intl api's

**Comment by RichardLindhout** [comment]
cc: https://github.com/MohamadKh75

**Comment by RichardLindhout** [comment]
cc: @MohamadKh75

**Comment by RichardLindhout** [comment]
Inspiration: https://github.com/MohamadKh75/react-native-jalali-datepicker

**Comment by RichardLindhout** [comment]
I think this example is what we need to support he day numbers in all languages!
https://codesandbox.io/s/mystifying-sammet-6jst7?file=/src/App.js

**Comment by RichardLindhout** [comment]
One thing which seems really hard is to get the number of days in the month in a universal way

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2020-08-20 om 22 45 12](https://user-images.githubusercontent.com/6492229/90823922-eb154400-e336-11ea-8b94-81a44a7ddce7.png)

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2020-08-20 om 22 47 15](https://user-images.githubusercontent.com/6492229/90824076-20219680-e337-11ea-8576-a67c946ff556.png)

Is it just my browser or something else?

**Comment by MohamadKh75** [comment]
> ![Schermafbeelding 2020-08-20 om 22 47 15](https://user-images.githubusercontent.com/6492229/90824076-20219680-e337-11ea-8576-a67c946ff556.png)
> 
> Is it just my browser or something else?

that's ok

**Comment by MohamadKh75** [comment]
> One thing which seems really hard is to get the number of days in the month in a universal way

As far as I searched, there is no way to do that using just `Intl` API!

**Comment by RichardLindhout** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar

I think we'll need this and make logic per calendar type

**Comment by matinzd** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/calendar
> 
> I think we'll need this and make logic per calendar type

Yes, it’s better to implement logic calendar per type. I can help you with this.

**Comment by RichardLindhout** [comment]
I don't feel like building this since I don't know anything about Persian calendars and will be hard to manage. Maybe some fork of this package can do it or a second maintainer
