### ISSUE TITLE
Day of the Week Picker

### ISSUE THREAD

**Issue by kaaax0815** [web-ridge/react-native-paper-dates#181]
A picker to select multiple days of the week

- [ ] Monday
- [ ] Tuesday
- [ ] Wednesday
- [x] Thursday
- [ ] Friday
- [x] Saturday
- [ ] Sunday

Something like you have when creating an alarm

**Comment by RichardLindhout** [comment]
If this is described by material ui spec we could add this but otherwise it's not something we will be building
