### ISSUE TITLE
Automatically changes the format 12h to 24h

### ISSUE THREAD

**Issue by ziya3435** [web-ridge/react-native-paper-dates#183]
Using: 
react-native@0.68.2 
react-native-paper-dates@0.8.7

There seems to be a bug with AM. I select AM times, it converts to PM times. Ex. I select 2:15AM and click OK, the params returns the object like that:
Object {
  "hours": 14,
  "minutes": 15,
}

**Comment by RichardLindhout** [comment]
Will look into this and release a fix!

**Comment by RichardLindhout** [comment]
Looks like this works now for me with english locale and expo 46 on iOS. I think someone else fixed it because I did not do anything. 

Please test with new release!

**Comment by RichardLindhout** [comment]
Will be released later this evening!
