### ISSUE TITLE
ReferenceError: Property 'Intl' doesn't exist

### ISSUE THREAD

**Issue by adilusman51** [web-ridge/react-native-paper-dates#184]
Expo SDK 46 with custom dev-client and expo-localization
Platform: iOS simulator

I am getting following error when trying to show Single Date Picker

```
ReferenceError: Property 'Intl' doesn't exist

This error is located at:
    in HeaderContentSingle (created by DatePickerModalContentHeader)
    in RCTView (created by View)
    in View (created by DatePickerModalContentHeader)
    in RCTView (created by View)
    in View (created by DatePickerModalContentHeader)
    in RCTView (created by View)
    in View (created by DatePickerModalContentHeader)
    in DatePickerModalContentHeader (created by DatePickerModalContent)
    in RCTSafeAreaView
    in SafeAreaView (created by DatePickerModalHeaderBackground)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by DatePickerModalHeaderBackground)
    in DatePickerModalHeaderBackground (created by DatePickerModalContent)
    in DatePickerModalContent (created by DatePickerModal)
    in RCTView (created by View)
    in View (created by DatePickerModal)
    in RCTView (created by View)
    in View (created by DatePickerModal)
    in RCTView (created by View)
    in View (created by AppContainer)
```
![Simulator Screen Shot - iPhone 13 - 2022-08-19 at 06 46 59](https://user-images.githubusercontent.com/26340587/185524863-2be2ab94-d209-4f4e-ad65-1a161eafecde.png)

**Comment by CosminGRG** [comment]
Install:
`npm install intl`
Then import at the top of your file:
`import 'intl';
import 'intl/locale-data/jsonp/en';`

**Comment by RichardLindhout** [comment]
Enable hermes on android don't use polyfills

**Comment by RichardLindhout** [comment]
Don't enable hermes on iOS yet Intl is not supported I think

**Comment by adilusman51** [comment]
Yes, Intl is not supported on iOS. It's support is coming in React Native
0.7 according to the react native docs

**Comment by RichardLindhout** [comment]
Use polyfill of readme or disable hermes on iOS (would recommend the last)

**Comment by adamchenwei** [comment]
@RichardLindhout its not true though. For me, i am using React Native 0.68.2. I still get the same error. so even its higher than 0.66, same error will still appear. can we reopen this ticket? or I also have to apply the same pollifill even I am higher than 0.66?
