### ISSUE TITLE
fixed width and height of DateRangePicker

### ISSUE THREAD

**Issue by SharfMohiuddin** [web-ridge/react-native-paper-dates#193]
![Simulator Screen Shot - iPhone 13 - 2022-08-29 at 11 36 13](https://user-images.githubusercontent.com/111132563/187172658-fca9cf04-728b-4e22-bfa6-28c9097ed513.png)
I have changed the size of this Date Range Picker by changing it from the library but its temporary , when I will put cmd npm install all my changes will be gone. Is there any way to get any prop of height and width ? or any other solution please help!

**Comment by JB712** [comment]
You can copy  the file that you changed and put it in your source folder (rename it and export it as "DateRangePickerCustom" to know which one your working with). Be aware of the imports that need to be done to make it work properly.
With this done _npm install_ will not override your changes but  be aware that you won't benefit the following updates (maybe it does if your component extends the original one).

This technic is applicable for any package that you want to custom 😉

**Comment by RichardLindhout** [comment]
See custom modal of web version you can choose your own modal than :)
