### ISSUE TITLE
AM - PM & Perrformance issue

### ISSUE THREAD

**Issue by ziya3435** [web-ridge/react-native-paper-dates#194]
Hi. 
I have experienced with date picker and time picker v.0.9.0 on android platform
Date picker is too slow. it appears after 5 seconds delay. I have to click twice to select a day. Once clicking is not enough to select date. 
Time picker's default mode is PM. If first I change the mode to AM and then set the time, it returns the time in PM format.
But first I set the time, then change the mode to AM, it returns the time in AM format. I always have to click AM after change the time.

**Comment by RichardLindhout** [comment]
Please add reproducible snack so we could fix this, currently it takes too much work to reproduce issues like this
