### ISSUE TITLE
Can't find variable: Intl

### ISSUE THREAD

**Issue by realmhamdy** [web-ridge/react-native-paper-dates#198]
I have a basic use case here, nothing fancy. Here's a [snack that shows the problem](https://snack.expo.dev/@realmhamdy/ranting-pastry) (click the button to open the modal). It works fine on the Web tab. It doesn't work on Android emulator though. I even installed Intl package in package.json.

**Comment by Mikkal24** [comment]
I had this issue as well but, I was able to follow the android caveats guide on the readme.md file. 

https://github.com/web-ridge/react-native-paper-dates#android-caveats

**Comment by realmhamdy** [comment]
@Mikkal24 Can you elaborate on how you fixed that exactly? I enabled Hermes locally (in an expo project) using `jsEngine: "hermes"` in `app.json` and now I'm getting a different error: `Can't read property 'mediem' of undefined`.

**Comment by RichardLindhout** [comment]
enableHermes and upgrade RN to at least specified version what version of expo are you using?

**Comment by realmhamdy** [comment]
expo `~46.0.9` RN `0.69.5`

**Comment by realmhamdy** [comment]
Maybe worth noting that I'm using the latest and greatest `react-native-paper@5.0.0-rc.5`. Dropping that to the lesser 4.x seems to have fixed the problem for me. I planned around using [SegmentedButtons](https://callstack.github.io/react-native-paper/segmented-buttons.html) though so that's a bummer.

**Comment by Mikkal24** [comment]
@realmhamdy sorry im a bit late on the reply but, I also got that error. I think the issue is simply that react native paper dates doesnt support Material Design 3 yet. 

I am only inferring this because using version 2 works for me. See my comment here:

https://github.com/web-ridge/react-native-paper-dates/issues/189#issuecomment-1243025636
