### ISSUE TITLE
Date range modal save label color is the same color as the modal header because they both are primary color, so save label doesn't show

### ISSUE THREAD

**Issue by saver711** [web-ridge/react-native-paper-dates#203]
![2022-09-19_19h57_41](https://user-images.githubusercontent.com/28202010/191083219-32376c31-9170-4992-939a-cedb19d42c22.png)
-----------------------------------
![2022-09-19_19h59_44](https://user-images.githubusercontent.com/28202010/191083286-601ba1c7-8429-48e4-9fbf-a93107f66713.png)
---------------------------------
![2022-09-19_19h58_04](https://user-images.githubusercontent.com/28202010/191083319-b299409f-d304-4a67-98d4-4159818ed3d2.png)

**Comment by saver711** [comment]
also i need to change close and edit icons colors to white

**Comment by manishhundekar** [comment]
![image](https://user-images.githubusercontent.com/52907613/191264686-b616ad9e-b2c4-444d-816e-033f6270b4ce.png)

This solved my issue. @saver711

**Comment by saver711** [comment]
@manishhundekar 
Doesn't work for me, i don't know why
![image](https://user-images.githubusercontent.com/28202010/191266795-ae2dea18-f8df-428d-ad70-14c7636bdd48.png)

**Comment by manishhundekar** [comment]
<Text> is imported from 'react-native-paper' right? @saver711

**Comment by saver711** [comment]
@manishhundekar 
no i was importing it from react native
now it works, thanks,
how do i change (save, exit, edit) color to white??
do i have do them all like this?
![image](https://user-images.githubusercontent.com/28202010/191269306-43f87df2-5540-4fe6-bad9-300bef8f24ca.png)

**Comment by alphazhe** [comment]
I am only using react-native-paper-dates lib, not using entire react-native-paper lib. Is there any way to fix this in such case?
