### ISSUE TITLE
Add react-native-paper theming

### ISSUE THREAD

**Issue by ianbrown-bearcode** [web-ridge/react-native-paper-dates#204]
I see that there are a number of issues having to do with colors. The react-native-paper project supports themes (https://callstack.github.io/react-native-paper/theming.html). The components in this module could use the react-native-paper theme for the regular react-native components as well as the react-native-paper components. This might address many of the color issues.

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/206
