### ISSUE TITLE
Date Input placeholder

### ISSUE THREAD

**Issue by lelimit** [web-ridge/react-native-paper-dates#212]
Place holder for date input is currently showing DD.MM.YYYY.

Add option to override with custom text or using locale

**Comment by RichardLindhout** [comment]
This is than the default of your locale, if your Intl implementation is right it can be overriden with the locale

**Comment by lelimit** [comment]
The month view / date chooser is showing my locale correctly but not the date input.

**Comment by lelimit** [comment]
![image](https://user-images.githubusercontent.com/43383775/208238360-d60f148f-b6ff-44a5-ad1c-ac050f70ab04.png)

**Comment by lelimit** [comment]
![image](https://user-images.githubusercontent.com/43383775/208238369-72c18498-813a-480b-895e-691a8cc885ea.png)

**Comment by RichardLindhout** [comment]
<img width="381" alt="Scherm­afbeelding 2022-12-17 om 13 48 22" src="https://user-images.githubusercontent.com/6492229/208242608-8e980050-6f2b-45af-bde0-4fee0fb6ab16.png">
<img width="403" alt="Scherm­afbeelding 2022-12-17 om 13 48 45" src="https://user-images.githubusercontent.com/6492229/208242609-b9620073-eb09-4691-9b4e-649165dd5b5f.png">

**Comment by RichardLindhout** [comment]
If I change locale to NL it does change it, what locale are you on?

**Comment by RichardLindhout** [comment]
It should do the default specified here based on locale:
https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by RichardLindhout** [comment]
Please add reproducible snack so we could fix this, currently it takes too much work to reproduce issues like this
