### ISSUE TITLE
Change the top bg color in date range.

### ISSUE THREAD

**Issue by vegulla001** [web-ridge/react-native-paper-dates#219]
I can't able to change the bg color for both top and bottom while selecting range.

**Comment by vegulla001** [comment]
> I can't able to change the bg color for both top and bottom while selecting range.

I want in different color not the purple which is default.

**Comment by iM-GeeKy** [comment]
The color is derived from the [Paper Theme](https://callstack.github.io/react-native-paper/theming.html).

**Comment by vegulla001** [comment]
@iM-GeeKy Can you provide some sort of demo in Sandbox or something on how to do that. I particularly like this package and it's design.
