### ISSUE TITLE
The format is not applied in the range edition fields, nor are states updated

### ISSUE THREAD

**Issue by JohabarWil** [web-ridge/react-native-paper-dates#233]
Hi, 

Version 0.11.10 is being used when implementing react-native-paper-dates in range mode, when entering to edit dates manually, the format is not applied, nor is the status of the entered dates updated

It was expected that when entering the dates in each field, the defined format would be applied, at the same time the status of the dates to save would be updated

NOTE: This was going to happen after migrating version of react-native-paper-dates from 0.9.2 to 0.11.10 (using react-native-paper V5.1.2)

Plays on iOS 12 and 16, Android 12,

configuration example

 <DatePickerModal
                locale={'en'}
                mode="range"
                visible={openPicker}
                onDismiss={onDismiss}
                startDate={range.startDate}
                endDate={range.endDate}
                onConfirm={confirmDate}
                disableStatusBar={Platform.OS !== 'ios'}
                validRange={{
                  startDate: new Date(clientCreationDate), 
                  endDate: new Date(),
                }}
                uppercase={false} // optional, default is true
                dateMode={'start'}
            />

![bug-range](https://user-images.githubusercontent.com/36446344/210834191-bb23c30e-16c2-4086-9ed0-be42b713f53a.png)

Can someone help me? something you are doing wrong?

**Comment by iM-GeeKy** [comment]
PRs welcome!
