### ISSUE TITLE
languages missing in index

### ISSUE THREAD

**Issue by JB712** [web-ridge/react-native-paper-dates#234]
Just to let you know, in 0.11.10 release, in **/src/index.tsx**, some languages are missing (like _fr_ or _ko_)

**Comment by iM-GeeKy** [comment]
Nice find @JB712. I put in a [PR](https://github.com/web-ridge/react-native-paper-dates/pull/235) to add the missing languages.

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/235
