### ISSUE TITLE
Setting time to 12:00 -> 00:00

### ISSUE THREAD

**Issue by SimonErlandsson** [web-ridge/react-native-paper-dates#239]
### Current behaviour

When selecting time 12 for the hour, it is set to 00 instead. Using 24h mode.

### Expected behaviour

When setting the time to ex. 12:00, the time should indeed be set to 12:00 instead of 00:00.

### How to reproduce?

Import date-picker, open up time-picker with 24h mode and select 12.

### Preview

https://user-images.githubusercontent.com/3949779/212188693-74909582-972e-41c3-8763-8e3378c20563.mp4

**Comment by iM-GeeKy** [comment]
PRs welcome!

**Comment by iM-GeeKy** [comment]
I might have some time to look into it this upcoming week. At first glance I did notice `00` is appearing twice in the clock. Its correct appearance should be as follows.
<img width="943" alt="Screenshot 2023-01-15 at 11 32 41 AM" src="https://user-images.githubusercontent.com/7604441/212553536-d6c1aaba-6aab-49e6-aa64-577c0dd77013.png">

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/247

**Comment by SimonErlandsson** [comment]
https://user-images.githubusercontent.com/3949779/217999406-f93e0b62-2382-4da5-b6f2-389947a7153c.mp4

Thank you. There seem to be some improvements with the new version. Although, if the current value entered for the hour is less than 12, then the behaviour is still wrong. See the clip attached.
