### ISSUE TITLE
switch timepicker modal format from am/pm to 24 hours

### ISSUE THREAD

**Issue by ganesh-papola** [web-ridge/react-native-paper-dates#24]
How to change am-pm to 24 hours format in date picker?

<img width="200" alt="Screenshot 2020-12-08 at 6 32 56 PM" src="https://user-images.githubusercontent.com/19851598/101487191-cd222c80-3983-11eb-9459-60673e855c68.png">

**Comment by RichardLindhout** [comment]
It depends on the device settings

**Comment by RichardLindhout** [comment]
It will probably fine for the end-users so change timezone and language settings on the device and it should render the right format for that timezone/language

**Comment by RichardLindhout** [comment]
@ganesh-papola did this fix it for you?

**Comment by ganesh-papola** [comment]
![Hours1 jpeg](https://user-images.githubusercontent.com/19851598/102237609-d62e7300-3f1a-11eb-95ee-faa88778d673.jpg)

**Comment by RichardLindhout** [comment]
Does this only happen on iOS? + do you have the latest version installed?

**Comment by ganesh-papola** [comment]
Yes in ios, I have 0.2.3v installed

**Comment by RichardLindhout** [comment]
Can't reproduce your latest screenshot on iphone 11 - 14.3.
What do you do exactly can you send some code?

You can now override the locale it will automatically detect it does not use 12 hour format in that locale
```
  <TimePickerModal
        locale="en"
        ....rest
/>
```

**Comment by RichardLindhout** [comment]
@ganesh-papola We improved some things on the TimePicker (mostly Android) is this problem still happening?

**Comment by ganesh-papola** [comment]
Its working, Thanks
