### ISSUE TITLE
Selected current date text color same as background

### ISSUE THREAD

**Issue by bombillazo** [web-ridge/react-native-paper-dates#240]
### Current behaviour
Selecting the current date will not show the date since it is the same color as the primary background select color.
It works on other non-current dates

### Expected behaviour
The date text color of the current date, when selected, contrasts with the select background color

### How to reproduce?
Add custom styling to your RN Paper theme.

### Preview
![image](https://user-images.githubusercontent.com/44002321/212359768-9ddd3ff7-390c-4967-95dc-2fd13ba39027.png)
![image](https://user-images.githubusercontent.com/44002321/212359403-0aaea48c-5326-47d3-b9ba-82b45f921813.png)

### What have you tried so far?
Not sure how to fix

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by RichardLindhout** [comment]
We need to check with the npm 'color' package if the color is ligth/dark to change text color

**Comment by iM-GeeKy** [comment]
I'll take a look this weekend.

**Comment by iM-GeeKy** [comment]
@bombillazo  Feel free to use [patch-package](https://github.com/ds300/patch-package) to apply the changes from this [pull request](https://github.com/web-ridge/react-native-paper-dates/pull/241) until we can get this merged.

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/241
