### ISSUE TITLE
Can you add interval? like 15 minutes?

### ISSUE THREAD

**Issue by tonvlad88** [web-ridge/react-native-paper-dates#242]
Can we add a feature for a time interval? This package is great and hope it can be added :)

Thank you.

**Comment by iM-GeeKy** [comment]
Hi @tonvlad88, unfortunately, I don't think we will be adding intervals to the time picker as it doesn't adhere to the material you [guidelines](https://m3.material.io/components/time-pickers/specs) on time pickers. @RichardLindhout  Please correct me if I'm misinterpreting the feature request. If this is something we can/should support PR's are always welcome.

**Comment by RichardLindhout** [comment]
@iM-GeeKy I agree, I think we should only implement material design specs and not go any further than that
