### ISSUE TITLE
startYear & endYear not working

### ISSUE THREAD

**Issue by giannismanie** [web-ridge/react-native-paper-dates#243]
I' ve set startYear={2023} & it did not worked, also I searched in node modules inside your code and saw that you set 1800 if startYear is not a number. So, I changed 1800 with 2023 and did not worked.
Any suggestion?

**Comment by iM-GeeKy** [comment]
Make sure the props are inside of `validRange`. Here are the [docs](https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/single-date-picker) for a single date picker, although I'm not sure what type of picker you are using.

**Comment by giannismanie** [comment]
https://snack.expo.dev/Xy8Uit7gm

I just added startYear={2023} prop & you can still scroll up to 2022.

**Comment by iM-GeeKy** [comment]
@giannismanie Thanks for providing an example, this does look like an issue. We'll get to this when we can, but if you need it immediately your best bet is to open a PR yourself. We'd be happy to help out.

**Comment by RichardLindhout** [comment]
This is ment to prevent too much years in year-picker we probably need to do something different for this. I would just let the user select everything and then show error message. Not a priority for us to build this into the date picker since there are a lot of different use-cases.
