### ISSUE TITLE
ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by tonvlad88** [web-ridge/react-native-paper-dates#246]
### Current behaviour
An error shows when displaying the time modal

### Expected behaviour
It should show the modal time picker

### How to reproduce?
click on the timer icon

### Preview
![Screenshot_1674313433](https://user-images.githubusercontent.com/40188798/213873037-53303151-6a61-4faa-a035-c1450f0ac024.png)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | Android API 34 x86_64
| react-native                | "0.68.2"
| react-native-paper    | ^5.1.3
| node                            | v18.12.1
| npm or yarn                | yarn 1.22.19
| expo sdk                     | "^45.0.0"

**Comment by iM-GeeKy** [comment]
See related https://github.com/web-ridge/react-native-paper-dates/issues/213, https://github.com/web-ridge/react-native-paper-dates/issues/184, https://github.com/web-ridge/react-native-paper-dates/issues/153.

Also check out [android caveats](https://web-ridge.github.io/react-native-paper-dates/docs/intro#android-caveats).

**Comment by tonvlad88** [comment]
> See related #213, #184, #153.
> 
> There are other resolved threads pertaining to this issue [here](https://github.com/web-ridge/react-native-paper-dates/issues?q=INTL+).
> 
> Also check out [android caveats](https://web-ridge.github.io/react-native-paper-dates/docs/intro#android-caveats).

adding this at app.json solved this bug. Thanks

```
...
"jsEngine": "hermes",
...
```
