### ISSUE TITLE
Text Date Modal

### ISSUE THREAD

**Issue by fendipramu92** [web-ridge/react-native-paper-dates#250]
Can i change textColor on Select Year Date Picker?
because default theme white color textColor year Select

**Comment by iM-GeeKy** [comment]
The text colors correspond to the following theme properties in Material Design 3 (https://m3.material.io/components/date-pickers/specs#d58626b9-ed69-4963-a75c-18d00cae5a06) which you can override in your [paper theme](https://callstack.github.io/react-native-paper/theming.html).

<img width="723" alt="Screenshot 2023-01-26 at 6 58 31 AM" src="https://user-images.githubusercontent.com/7604441/214829917-a9f80638-f6e3-4085-a334-6de7a2806359.png">

**Comment by fendipramu92** [comment]
Thanks, im using MD2 and migrate to MD3 for RNPaper 5x, 
solved
