### ISSUE TITLE
Type error required to add accessibilityLabelledBy, accessibilityLanguage

### ISSUE THREAD

**Issue by nityanantan23** [web-ridge/react-native-paper-dates#254]
### Current behaviour
produces a type error where it is required to add accessibilityLabelledBy, accessibilityLanguage  
The fixed PR from react native paper : https://github.com/callstack/react-native-paper/pull/3603

### Expected behaviour
Shouldn't produce the type error, initially it was in react native paper as well but in the latest build they fixed it

### How to reproduce?
https://snack.expo.dev/@nity/witty-pudding
same code as in the example
https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/input-date-picker

### Preview
![image](https://user-images.githubusercontent.com/48348087/216499945-a752ae59-5571-4305-a358-ccf55249b7df.png)

### What have you tried so far?
none

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71.1
| react-native-paper    | 5.1.4
| node                            | x.x.x
| npm or yarn                | 1.22.19
| expo sdk                     | x.x.x

**Comment by nityanantan23** [comment]
https://snack.expo.dev/@nity/witty-pudding

**Comment by iM-GeeKy** [comment]
This is resolved in `0.14.0`. https://snack.expo.dev/@fitzwabs/602241
