### ISSUE TITLE
white headerBackground in v 0.11.14

### ISSUE THREAD

**Issue by poy004id** [web-ridge/react-native-paper-dates#257]
### Ask your Question

i update from 0.11.11 because in some android device it is so slow. It feel faster in 0.11.14 but the header is not in primary color.

Here is the screenshot in android : 
![Screenshot_1677160667](https://user-images.githubusercontent.com/54522566/220931807-7b9b8e0f-18e6-45c8-b17c-8813b0f9f0fe.png)

And this is the repro : 
https://snack.expo.dev/@7marrch/react-native-paper-dates-headerbackground

thank you in advance

**Comment by iM-GeeKy** [comment]
The color of the container corresponds to the `surface` attribute in the theme and is that way so that it adheres to the [MD3 date picker](https://m3.material.io/components/date-pickers/specs).

**Comment by poy004id** [comment]
ok, thank you
