### ISSUE TITLE
Content of date picker modal is in StatusBar on iOS

### ISSUE THREAD

**Issue by vlkpa** [web-ridge/react-native-paper-dates#258]
Content of date picker modal is in StatusBar. This line [StatusBar.currentHeight](https://github.com/web-ridge/react-native-paper-dates/blob/6f1078c80f84f86ce3e36a1cc41c523e68b24b49/src/Date/DatePickerModal.tsx#L107) is null on iOS.
Maybe something like [this hook](https://gist.github.com/brayhoward/82ed6a68ed2c3727a67cd6e0863d6a1c) could be better for getting status bar height

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by lelimit** [comment]
![image](https://user-images.githubusercontent.com/43383775/236121715-333e39e5-86dd-4b39-9494-28f98ac4dd30.png)

**Comment by RichardLindhout** [comment]
We should use the useSafeareaInsets from react-native-safe-area-context

**Comment by RichardLindhout** [comment]
Will be fixed in next release!
