### ISSUE TITLE
Hour/Minute text is not localized in TimePickerModal -  keyboard mode

### ISSUE THREAD

**Issue by vlkpa** [web-ridge/react-native-paper-dates#259]
There is no localization for [Hour ](https://github.com/web-ridge/react-native-paper-dates/blob/6f1078c80f84f86ce3e36a1cc41c523e68b24b49/src/Time/TimeInputs.tsx#L114) and [Minute](https://github.com/web-ridge/react-native-paper-dates/blob/6f1078c80f84f86ce3e36a1cc41c523e68b24b49/src/Time/TimeInputs.tsx#L176) texts

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by RichardLindhout** [comment]
Fixed!
