### ISSUE TITLE
is there a way to use a different keyboard?

### ISSUE THREAD

**Issue by jpatricksweeney** [web-ridge/react-native-paper-dates#267]
Hello,
Question...is there a way to use a different keyboard?  On iOS and Android, the keyboard that appears is numeric which means there's no way to enter the date manually (modal works great) because there's no forward slash character.  Or perhaps I'm missing something?
Thanks in advance,
Patrick

**Comment by jpatricksweeney** [comment]
Hi @iM-GeeKy Brandon,  thanks so much!

**Comment by iM-GeeKy** [comment]
Hey @jpatricksweeney feel free to test this out. I threw it together quickly, but it should address the problem I believe https://github.com/web-ridge/react-native-paper-dates/pull/269

**Comment by jpatricksweeney** [comment]
thanks Brandon!  I’ll test it out first thing tomorrow.

**Comment by jpatricksweeney** [comment]
@iM-GeeKy Hey Brandon,  I tested it in my local env and all looked good (slashes are automatically injected).  Will this be pushed up to main branch soon?
many thanks!
Pat

**Comment by iM-GeeKy** [comment]
> @iM-GeeKy Hey Brandon, I tested it in my local env and all looked good (slashes are automatically injected). Will this be pushed up to main branch soon? many thanks! Pat

Hey dude, check out this [comment](https://github.com/web-ridge/react-native-paper-dates/pull/269#issuecomment-1474871778). There is a temporary patch you can use while I can come up with a proper solution that works for everyone.

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/269
