### ISSUE TITLE
Support only minutes and seconds

### ISSUE THREAD

**Issue by brunohkbx** [web-ridge/react-native-paper-dates#27]
Hello everyone.
I was wondering if you guys have plans to support minutes and seconds mode. It's not on material design docs but it could be useful.

For instance, check this example:
https://material-ui-pickers.dev/demo/timepicker

![Screenshot from 2020-12-22 16-29-35](https://user-images.githubusercontent.com/6487206/102925895-f4dcbe80-4472-11eb-8bc3-7eaca64f5e6f.png)

**Comment by RichardLindhout** [comment]
For now we only plan to support described features from the material design specs or use cases we need ourself. So if we come across the use case of seconds we will maybe make this or provide more access to the internal components like Analog Clock so user could more easily build their own picker

**Comment by brunohkbx** [comment]
Exposing the internal components sounds good. Maybe eventually you could add a section in the README explaining how to create custom pickers.
