### ISSUE TITLE
Dark mode year selector does not use darkmode onSurface or text color for older theme

### ISSUE THREAD

**Issue by jennifersalas** [web-ridge/react-native-paper-dates#277]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-paper-dates@0.15.1` for the project I'm working on.

I use v2 of the react-native paper theme, and when using dark mode, the year text shows as dark text. Replacing the color value from undefined to either `theme.colors.text` or `theme.colors.onSurface` fixes the issue

| Dark mode without fix | Dark mode with fix |
|---|---|
|![simulator_screenshot_E91662DE-15E1-486D-8878-8F90E26299D9](https://user-images.githubusercontent.com/12005979/231274610-1d84136a-7321-4a80-a889-d0b270ba2a2f.png)|![simulator_screenshot_97DDC140-479A-4F9F-91DE-898BBD851F9F](https://user-images.githubusercontent.com/12005979/231274915-6047b737-d939-493b-b573-5001c29eb9d5.png)|

Here is the diff that solved my problem:
```diff
diff --git a/node_modules/react-native-paper-dates/src/Date/YearPicker.tsx b/node_modules/react-native-paper-dates/src/Date/YearPicker.tsx
index 3178557..a4a23d6 100644
--- a/node_modules/react-native-paper-dates/src/Date/YearPicker.tsx
+++ b/node_modules/react-native-paper-dates/src/Date/YearPicker.tsx
@@ -105,7 +105,7 @@ function YearPure({
                 : {
                     color: theme.isV3
                       ? theme.colors.onSurfaceVariant
-                      : undefined,
+                      : theme.colors.onSurface,
                   },
               { ...textFont },
             ]}
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by iM-GeeKy** [comment]
Hi @jennifersalas thanks for finding this and providing the fix. I've created https://github.com/web-ridge/react-native-paper-dates/pull/278 and @RichardLindhout will merge it when he's available. Until then, just use the your patch.

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/278
