### ISSUE TITLE
Header displaying one day behind

### ISSUE THREAD

**Issue by albertwickman** [web-ridge/react-native-paper-dates#279]
[###]([url](url)) Current behaviour
When in the DatePickerModal, the header, shows one day behind as seen in the image below

### Expected behaviour
That the same date is shown in the header, as the date(s) that are selected in the picker.

### Preview
![Screenshot_2023-03-23_123642](https://user-images.githubusercontent.com/58918868/231827795-e43ac0f8-316b-4dff-98d2-9a10eb7b7c0d.png)

### What have you tried so far?
Trying to modify dates that are passed into the DatePickerModal

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            |14.15.0
| npm                             | 7.21.0

**Comment by Za-Sing** [comment]
I can confirm this issue, here is a repro based on the official snack example: https://snack.expo.dev/oXbouiz8S

Using that Date as a value, it displays one day behind in the input and the picker

**Comment by iM-GeeKy** [comment]
Here is a working example https://snack.expo.dev/@fitzwabs/2148fb, note the date format. Here's a [thread](https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off) explaining the bizarre behavior when using a format such as `YEAR-MONTH-DAY`.
