### ISSUE TITLE
Use of DatePickerInput crashes on Android 

### ISSUE THREAD

**Issue by lelimit** [web-ridge/react-native-paper-dates#280]
### Current behaviour
App crashes when loading component using DatePickerInput

### Expected behaviour
No crash

### How to reproduce?

<DatePickerInput
              style={styles.input}
              mode='outlined'                                                
              label={startDateLabel}
              value={startDate}
              onChange={(d) => {
                  setStartDate(d)
              }}
              inputMode='start'
              withDateFormatInLabel={false}           
          />

ERROR  ReferenceError: Can't find variable: Intl

Call stack
React.useMemo$argument_0
...\src\Date\dateUtils.tsx

**Comment by iM-GeeKy** [comment]
See related https://github.com/web-ridge/react-native-paper-dates/issues/213, https://github.com/web-ridge/react-native-paper-dates/issues/184, https://github.com/web-ridge/react-native-paper-dates/issues/153, https://github.com/web-ridge/react-native-paper-dates/issues/246

There are other resolved threads pertaining to this issue [here](https://github.com/web-ridge/react-native-paper-dates/issues?q=INTL+).

Also check out [android caveats](https://web-ridge.github.io/react-native-paper-dates/docs/intro#android-caveats).

**Comment by lelimit** [comment]
Thanks. I solved this by changing js engine to hermes
