### ISSUE TITLE
Align modal title to MD3 guidelines for full-screen dialogs

### ISSUE THREAD

**Issue by fabriziocucci** [web-ridge/react-native-paper-dates#282]
Based on [MD3 guidelines for full-screen dialogs](https://m3.material.io/components/dialogs/guidelines#6932d2ef-df7c-4b53-8635-da2b5e82f7c2), I believe the label should appear in the top app bar, next to the `X` icon.

Is there a chance to align to the guideline or provide an option to decide where the label should be placed?

![header](https://user-images.githubusercontent.com/8156463/232329144-173f4355-24cc-4f4f-ab84-fea149df7c5d.jpeg)

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by RichardLindhout** [comment]
Good point, we want to keep support for m2 as long as react-native-paper also has support for it but we can check the theme.isV3 to align with the guidelines. PR is welcome indeed,!
