### ISSUE TITLE
Range active indicator color not showing properly

### ISSUE THREAD

**Issue by Strengthless** [web-ridge/react-native-paper-dates#283]
### Current behaviour

The color of active indicator for `Range date picker` remains light purple, while primary color is set to dark red...

### How to reproduce?
```js
const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#1F1717',
  },
};
```

### Preview
<img src="https://user-images.githubusercontent.com/40143583/236793889-7dacc7c8-3624-40b8-9a51-f5cb59dcebb8.png" height="250">

**Comment by Strengthless** [comment]
Looks like you have to declare the color for `primaryContainer`... 

Apparently it's not calculated automatically based on `primary`??

Can close now, if this is intended behaviour.

**Comment by iM-GeeKy** [comment]
The underlying theming is derived from the parent library https://callstack.github.io/react-native-paper/docs/guides/theming.
