### ISSUE TITLE
Maximum Date Range that can be selected

### ISSUE THREAD

**Issue by sachinjnd** [web-ridge/react-native-paper-dates#287]
**Is your feature request related to a problem? Please describe.**
I want the user to be able to select only upto maximum range of 3 months

**Describe the solution you'd like**
Whenever user selects a start date, the dates after maximum possible range are grayed out

**Describe alternatives you've considered**
When user selects outside range, I will show them a dialog to select within the range

**Additional context**

**Comment by RichardLindhout** [comment]
This should already work with onChange & validRange
