### ISSUE TITLE
Feature Request: min/max date in range picker

### ISSUE THREAD

**Issue by Devathedeveloper** [web-ridge/react-native-paper-dates#29]
Adding MinDate Prop will be so usefull while selecting Dates Now We Can able to select previous dates also I want the User select after today Dates only

**Comment by RichardLindhout** [comment]
Agreed, this should be added

**Comment by RichardLindhout** [comment]
Added in 0.4.0

**Comment by RichardLindhout** [comment]
Thanks @nandorojo <3!

**Comment by cobap** [comment]
Hello Richard

I made a search for this prop but was not able to make it work.

Should I be using startDate inside validRange? If so, by just placing as new Date() is not blocking to select previous dates

I'm new to react and trying looking on the source code, but was not able to find the correct prop

Thanks in advance.,

**Comment by rathierry** [comment]
Hi @RichardLindhout,

which props are used to set min/max date in single date picker ?

Thanks

**Comment by RichardLindhout** [comment]
Same props inmulti and single

```
        validRange={{
         startDate: new Date(2021, 1, 2),  // optional
          endDate: new Date(2021, 3, 3), // optional
        }}
 ```

**Comment by nandorojo** [comment]
I'd also recommend memoizing the dates

**Comment by RichardLindhout** [comment]
If i'm not mistaken we pick the unix date from it and it won't re render if the underlying unix number does not change

**Comment by RichardLindhout** [comment]
@nandorojo is right you should memoize it, maybe I'll change it to be more protective of re-rendering and only sending the unix dates down.

**Comment by RichardLindhout** [comment]
```
const validRange = React.useMemo(()=>{
return {
         startDate: new Date(2021, 1, 2),  // optional
          endDate: new Date(2021, 3, 3), // optional
        }}
},[])
```

```
<DatePickerThingey  validRange={validRange}/>
```
