### ISSUE TITLE
can we set width and height of the calender

### ISSUE THREAD

**Issue by UttiKalyan** [web-ridge/react-native-paper-dates#291]
Is there any chance to set the height and width of the calender

**Comment by iM-GeeKy** [comment]
Here is an [old code example](https://github.com/web-ridge/react-native-paper-dates/blob/afcb7a912f5980777544e0e37887a124522a8242/example/src/App.tsx#L279) for a custom modal. If this issue is critical for you, please consider sending a pull request to fix it.
