### ISSUE TITLE
Is there any way to vertically align the calendar icon for the DatePickerInput in "outlined" mode

### ISSUE THREAD

**Issue by JPStrydom** [web-ridge/react-native-paper-dates#298]
When rendering the `DatePickerInput ` with `mode="outlined"`, the calendar icon is not vertically aligned within the input box:

![image](https://github.com/web-ridge/react-native-paper-dates/assets/25905330/97bbe8c1-53bd-4a4e-b836-10a22f2e0076)

I can't seem to find a styling option to style the calendar icon - I've tried `style`, `underlineStyle`, `outlineStyle`, and `contentStyle` but not of these seemed to work.

Is there a way to vertically align of style the icon?

**Comment by JPStrydom** [comment]
This is quite easy to replicate on the [official DatePickerInput snack](https://snack.expo.dev/@fitzwabs/react-native-paper-dates-input) with the following code:
```
import React from "react";
import { View, Text } from "react-native";
import { DatePickerInput } from 'react-native-paper-dates';
import { SafeAreaProvider } from "react-native-safe-area-context";

export default function App() {
  const [inputDate, setInputDate] = React.useState(undefined)

  return (
    <SafeAreaProvider>
      <View style={{justifyContent: 'center', flex: 1, alignItems: 'center'}}>
        <DatePickerInput
          locale="en"
          label="Birthdate"
          value={inputDate}
          onChange={(d) => setInputDate(d)}
          inputMode="start"
          mode="outlined"
        />
      </View>
    </SafeAreaProvider>
  );
}
```

The will produce the following misaligned icon:
![image](https://github.com/web-ridge/react-native-paper-dates/assets/25905330/574f7dae-79e8-4045-95b7-0dbe6ec83ccc)

**Comment by iM-GeeKy** [comment]
@JPStrydom Thanks for opening this issue. If this issue is critical for you, please consider sending a pull request to fix it. If not, we will do our best to get it resolved when available.

**Comment by SoyDiego** [comment]
I think this issue can be closed, right?
I can see in `mode="outlined"` perfectly centered.

![image](https://github.com/web-ridge/react-native-paper-dates/assets/19764334/ec233460-4343-4f18-8f8f-4bed238168d2)

**Comment by JPStrydom** [comment]
> I think this issue can be closed, right?
> I can see in `mode="outlined"` perfectly centered.
> 
> ![image](https://github.com/web-ridge/react-native-paper-dates/assets/19764334/ec233460-4343-4f18-8f8f-4bed238168d2)
> 

Has there been an update to the library recently?

**Comment by SoyDiego** [comment]
> > I think this issue can be closed, right?
> > I can see in `mode="outlined"` perfectly centered.
> > ![image](https://user-images.githubusercontent.com/19764334/263067241-ec233460-4343-4f18-8f8f-4bed238168d2.png)
> 
> Has there been an update to the library recently?

Sorry, my last screenshot was in Linux. Now I'm in Windows and I can see the problem.
Very weird. I will try to solve it later.

![image](https://github.com/web-ridge/react-native-paper-dates/assets/19764334/9b276e6b-1115-4160-9b56-d446e319fd1b)

Thanks!

**Comment by SoyDiego** [comment]
@JPStrydom I did a PR and I think  solves the problem.
If you can check it will be great: https://github.com/web-ridge/react-native-paper-dates/pull/315

**Comment by JPStrydom** [comment]
> @JPStrydom I did a PR and I think  solves the problem.
> If you can check it will be great: https://github.com/web-ridge/react-native-paper-dates/pull/315
> 
> 

The code looks good. Will let you know if it works once it's gone live 👍

**Comment by SoyDiego** [comment]
> > @JPStrydom I did a PR and I think  solves the problem.
> > If you can check it will be great: #315
> 
> The code looks good. Will let you know if it works once it's gone live 👍

The release is done and works perfectly on windows and Linux
