### ISSUE TITLE
Change edit icon color

### ISSUE THREAD

**Issue by sdfricke** [web-ridge/react-native-paper-dates#299]
### Ask your Question
Hello, I am updating the version of this package, and the pencil edit icon in the modal header is now black.  I don't see a prop available to change it back to white like it was in version 0.8.x.  If I update the theme to use white for the theme.colors.text, then the numbers in the calendar are also white and can't be seen.  Wondering if there is a way to just target the color of the edit icon?  Thank you.

![Screen Shot 2023-06-22 at 4 38 28 PM](https://github.com/web-ridge/react-native-paper-dates/assets/12498671/c3e00d60-b741-421b-9b16-59f52a018042)

**Comment by iM-GeeKy** [comment]
@sdfricke Hi, the color of the icon in [version 3](https://callstack.github.io/react-native-paper/docs/guides/theming#theme-properties) currently corresponds to `onSurface`. Hopefully that helps.

**Comment by sdfricke** [comment]
> @sdfricke Hi, the color of the icon in [version 3](https://callstack.github.io/react-native-paper/docs/guides/theming#theme-properties) currently corresponds to `onSurface`. Hopefully that helps.

Thanks for getting back to me @iM-GeeKy!  I don't believe I'm using v3, because changing onSurface changes day of the week and month/year text.  Sorry for my ignorance, but is there a way to do this while not using version 3?  And if I wanted to use version 3, would that be as simple as just adding `version: 3` to my theme object?  I tried that but it didn't seem to work.
![Screen Shot 2023-06-22 at 4 58 47 PM](https://github.com/web-ridge/react-native-paper-dates/assets/12498671/d05f2b02-e863-47a8-b50c-1449edfc7e27)

**Comment by iM-GeeKy** [comment]
Yeah, we are using the theme object from the parent library [react-native-paper](https://callstack.github.io/react-native-paper/docs/guides/theming). If you still think there is a bug, then feel free to create a reproducible example.

**Comment by JacobWNutrien** [comment]
Can we re-open this? I can't find a workaround to change the `editIcon` color even after adding `version: 3` and setting `onSurface` to my desired `editIcon` color. [Here's a reproducible example](https://snack.expo.dev/@jacobwnutrien/react-native-paper-dates-pencil-icon-color)
