### ISSUE TITLE
Initial date value

### ISSUE THREAD

**Issue by soto0** [web-ridge/react-native-paper-dates#305]
How do I set the initial value for the DatePickerInput. When I try to do this, when I try to open a modal with a date picker, I get undefined is not a function?

**Comment by iM-GeeKy** [comment]
Feel free to check out the docs for the [DatePickerInput](https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/input-date-picker). It has a working example.

**Comment by soto0** [comment]
[here I am trying to pass the initial value for the date

```javascript
     useEffect(() => {
        if (item) {
            setValue("date", dayjs(item.date) || undefined, { shouldValidate: false });
        }
    }, [item]);
 
                     <Controller
                        control={control}
                        name="date"
                        rules={{ required: true }}
                        render={({ field: { onChange, value } }) => (
                            <DatePickerInput
                                label="Дата"
                                value={value}
                                locale="ru"
                                mode="outlined"
                                inputMode="start"
                                withDateFormatInLabel={false}
                                onChange={onChange}
                            />
                        )}
                    />
```](url)

**Comment by iM-GeeKy** [comment]
My recommendation would be to get a simplistic example working such as the one in the [docs](https://snack.expo.dev/@fitzwabs/react-native-paper-dates-input). This would rule out the issue is with your setup in particular.

**Comment by soto0** [comment]
in the documentation, I see that they are passing undefined, but I don’t see that it shows how to pass any date

**Comment by iM-GeeKy** [comment]
I updated the snack https://snack.expo.dev/@fitzwabs/react-native-paper-dates-input
