### ISSUE TITLE
Issue In the Locale

### ISSUE THREAD

**Issue by KelisSuthar** [web-ridge/react-native-paper-dates#307]
Hello When I install the library in react native and run the project on Android or ios it shows me an issue like this 
[react-native-paper-dates] The locale en is not registered, see README!, key: typeInDate 
in several keys also on the Android side close and edit icons are not proper these are default icons.
![Screenshot_1691682598](https://github.com/web-ridge/react-native-paper-dates/assets/92707112/10cf0cc2-3f24-4080-ace2-52fbf810bf3a)
My library Version is
"react-native-paper-dates": "^0.18.13",
"react": "18.2.0",

**Comment by Eprince-hub** [comment]
This reported error doesn't happen in https://snack.expo.dev/ and might also not happen in expo projects. I have the same error, and I am using a bare-bone react native for my project, I strongly believe it is the same with the poster

<img width="1072" alt="Screenshot 2023-08-11 at 16 56 33" src="https://github.com/web-ridge/react-native-paper-dates/assets/74430629/2a3a30e7-0ad2-4915-950a-643d0481d52c">

**Comment by Eprince-hub** [comment]
Hey, i am providing a reproduction to the error here in the repo
https://github.com/Eprince-hub/react-native-date-picker-error

Steps to reproduce

Clone the repo & cd into project
```
git clone https://github.com/Eprince-hub/react-native-date-picker-error.git && cd react-native-date-picker-error
```
Install all Dependencies
```
yarn init-deps
```
Start & run both ios & android
```
yarn start-all
```

Click on `pick single date` and see the error
There is a total of ten errors, clicking on `dismiss` will reveal next error

**Comment by Eprince-hub** [comment]
@KelisSuthar Have you found a solution to the error?, if not maybe you can open the issue again?, my comment above wasn't a solution, i was explaining the project where the error is happening

**Comment by sambbaahh** [comment]
Have someone found a solution? I have the same error

**Comment by RichardLindhout** [comment]
Please see the example index.js we register translations https://web-ridge.github.io/react-native-paper-dates/docs/intro#register-translation
