### ISSUE TITLE
Error: Unable to resolve module react-native-paper

### ISSUE THREAD

**Issue by Crafter-Y** [web-ridge/react-native-paper-dates#310]
### Current behaviour
My eas build fails

### Expected behaviour
It sould not fail.

### How to reproduce?
I just use the package in my project [Crafter-Y/csa-frontend](https://github.com/Crafter-Y/csa-frontend)
I use the Version 0.18.12 with Expo 49.0.6

### Preview
![Screenshot_6](https://github.com/web-ridge/react-native-paper-dates/assets/71288761/79ba3ca9-2fb0-4414-a7c5-c305dfaa9ec3)

### What have you tried so far?
I don't know what to do. It seems like there is a node module missing, but I don't know why

### Your Environment

| software                      | version
| --------------------- | -------
| node                            | idk what eas uses
| npm or yarn                | whatever was uses (enabled legacy-peer-deps)
| expo sdk                     | 49.0.6

**Comment by iM-GeeKy** [comment]
@Crafter-Y You'll need to install `react-native-paper` is my guess. Go ahead and give that a try and see if it resolves your issue.

**Comment by Crafter-Y** [comment]
This seems to work. But I wonder why the dependency was not installed automatically. This could be a bug related to eas by expo
