### ISSUE TITLE
On Windows you cannot use yarn bootstrap

### ISSUE THREAD

**Issue by SoyDiego** [web-ridge/react-native-paper-dates#314]
### Current behaviour

@RichardLindhout @iM-GeeKy 
I tried in 3 differents laptops and I always use yarn. I tried to install doing `yarn bootstrap` and nothing is happening.
All time I was thinking is my problem but inside your project is the only place where is not working.
In Linux works perfectly.

### Expected behaviour

Can use in Windows too.

### Preview

![problem](https://github.com/web-ridge/react-native-paper-dates/assets/19764334/fd2f9cf9-78f9-4c3a-925f-52981dabb65f)

**Comment by iM-GeeKy** [comment]
Hi @SoyDiego unfortunately I don't have a windows machine, so I'm not sure how much help I can be here to implement and validate a solution. If this is something you want to tackle and open a pull request for that'd be great. I'm sure others might find it useful in the feature that contribute to the project and also use windows.

**Comment by SoyDiego** [comment]
> Hi @SoyDiego unfortunately I don't have a windows machine, so I'm not sure how much help I can be here to implement and validate a solution. If this is something you want to tackle and open a pull request for that'd be great. I'm sure others might find it useful in the feature that contribute to the project and also use windows.

I don't use Windows. 
I have Linux in my laptop and Windows only in my work. In my work I cannot "play" with this things.
I have 2 PR to do right now ( maybe solving https://github.com/web-ridge/react-native-paper-dates/issues/298 and  https://github.com/web-ridge/react-native-paper-dates/issues/309), but now I have the doubt if in Windows will be ok because sometimes in Linux the alignment change a little bit cause by the font or things like that.

And I'm trying to help but sometimes is difficult when you are alone fighthing with something that you didn't write and you ask for help and anyone reply. Is like the project is dead

**Comment by JoanGil** [comment]
Hi all! I have been investigating a bit this issue since I have a windows machine and it seems that the yarn command is not working because its behavior is changed. I commented the line from the `bootstrap.js` file:

`# yarn-path "scripts/bootstrap.js"`

And everything worked like a charm. If you want I can make the pull request.

**Comment by iM-GeeKy** [comment]
> Hi all! I have been investigating a bit this issue since I have a windows machine and it seems that the yarn command is not working because its behavior is changed. I commented the line from the `bootstrap.js` file:
> 
> `# yarn-path "scripts/bootstrap.js"`
> 
> And everything worked like a charm. If you want I could make the pull request.

If commenting it out works, my guess is the `bootstrap.js` is failing silently on windows. Ideally, I think that addressing that issue would be the better fix as we could pass this along to the folks at [paper](https://github.com/callstack/react-native-paper/discussions/4046) who seem to be plagued by the same issue.

**Comment by JoanGil** [comment]
Okay, could anyone with linux check that yarn still works? If it works I can do the one-line merge request 😆

**Comment by SoyDiego** [comment]
> Okay, could anyone with linux check that yarn still works? If it works I can do the one-line merge request 😆

Thanks @JoanGil. 
I tried in Linux and commenting the line continue working, but I don't know if it is the best solution.
Also I tried to implement a `try/catch` in `bootstrap.js`in **Windows** to see if I can get errors or more information but I didn't have anything.

Maybe @JoanGil you can write here in this post your workaround with all the steps that you did to run the project in Windows and use that information temporary until the people of [callstack reply us](https://github.com/callstack/react-native-paper/discussions/4046) and they help us to find a solution. Will help future users with Windows and with the same problem, your steps.

What do you think, @iM-GeeKy?

Thanks again both

**Comment by iM-GeeKy** [comment]
I think for now we can add a blurb to our [Contributing Guide](https://web-ridge.github.io/react-native-paper-dates/docs/contributing) to provide window users with a workaround until we can find a proper solution. I don't have a windows machine, so this isn't very easy to troubleshoot on my end. If were looking into this along with the `try/catch` I would verify it even reaches `bootstrap.js` as well.

**Comment by JoanGil** [comment]
Okay, I will debug a bit more the error and update the [Contributing Guide](https://web-ridge.github.io/react-native-paper-dates/docs/contributing) with the steps I followed to make it work on a Windows machine.

**Comment by iM-GeeKy** [comment]
Closing for now since we can use the temporary solution provided in the [contributing guide](https://github.com/web-ridge/react-native-paper-dates/pull/328)
