### ISSUE TITLE
Date input field no longer responds to width changes on web

### ISSUE THREAD

**Issue by JPStrydom** [web-ridge/react-native-paper-dates#324]
### Current behaviour

When running on web (with React Native Web) the `DateInputField` does not scale to the width of it's parent container, where it used to do so. 

Here is the behavior on version `0.18.19`:
![rnpd-new](https://github.com/web-ridge/react-native-paper-dates/assets/25905330/a5677473-e5d3-451d-935c-6ec6d4ac1f10)

### Expected behaviour

The `DateInputField` should respond to width changes on web. 

Here is the behavior on version `0.18.14`:
![rnpd-old](https://github.com/web-ridge/react-native-paper-dates/assets/25905330/c2508f5a-d237-4692-bc57-0fbf6de10f74)

### How to reproduce?

Place the `DateInputField` in a `View` that scales to 100% of available width:
```
<View style={{ width : '100%' }}>
  <DatePickerInput {...props}  />  
</View>
```

### What have you tried so far?

Changing the following code in `src/Date/DatePickerInputWithoutModal.tsx` seems to fix the issue:
```
const styles = StyleSheet.create({
  root: {
    flexGrow: 1,
    width: '100%', // Adding this to all these styles fixes the issue
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  inputContainer: {
    flexGrow: 1,
    width: '100%', // Adding this to all these styles fixes the issue
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  input: {
    flexGrow: 1,
    width: '100%', // Adding this to all these styles fixes the issue
  },
})
```

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.71.8
| react-native-paper    | ^5.10.3
| react-native-web       | ~0.18.12
| node                            | 18.16.0
| npm                            | 9.5.1
| expo sdk                     | ^48.0.20

**Comment by JPStrydom** [comment]
I've created a [PR](https://github.com/web-ridge/react-native-paper-dates/pull/326) which should address this issue.

**Comment by iM-GeeKy** [comment]
@JPStrydom I think this may not work for mobile, but using `width: Platform.OS === 'web' ? '100%' : undefined,` would solve the problem and fix the issue on mobile. If your issue was only present on web.

![simulator_screenshot_D84F4DBF-CCCD-491B-A301-57B78A5682E1](https://github.com/web-ridge/react-native-paper-dates/assets/7604441/37630a1e-cbbf-437e-b28d-90f8266319c5)

**Comment by SoyDiego** [comment]
Hi @JPStrydom.
I have created a new PR: https://github.com/web-ridge/react-native-paper-dates/pull/329
If you can check it too, would be perfect to test all devices and ways.
I think with my code I solved both issues:
- When we have a element on the left.
- The responsiveness in Web.

I hope be the correct solution :), If not, we will continue researching.

**Comment by JPStrydom** [comment]
I'll take a look at the new version today and confirm if it's still working on web 👍

**Comment by SoyDiego** [comment]
> I'll take a look at the new version today and confirm if it's still working on web 👍

Great, I will wait.
Thanks

**Comment by JPStrydom** [comment]
> I'll take a look at the new version today and confirm if it's still working on web 👍

Looks like all is still in order on the web version 👍

**Comment by SoyDiego** [comment]
> 

Great, thanks for your confirmation. Happy all is working ok 👌
