### ISSUE TITLE
DatePickerInput - please add icon size prop

### ISSUE THREAD

**Issue by roys-qlog-co** [web-ridge/react-native-paper-dates#332]
hi
please add to DatePickerInput iconStyle or iconSize prop

tnx Roy

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by SoyDiego** [comment]
> hi please add to DatePickerInput iconStyle or iconSize prop
> 
> tnx Roy

Hi @roys-qlog-co.
I have created a PR adding 3 new props: `iconSize`, ìconStyle` and `iconColor`.
You can check here https://github.com/web-ridge/react-native-paper-dates/pull/333.

Thanks
