### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by itsmetambui** [web-ridge/react-native-paper-dates#34]
Hello guys!
I'm facing an issue when I using react-native-paper-dates (lasted version **v0.2.12**) on **React Native + NextJS (SSR).**
Could you help me to resolve the problem? 
Thank you 

![image](https://user-images.githubusercontent.com/39029320/103988054-0686cb80-51c0-11eb-8948-3b8281fb399c.png)

**Comment by RichardLindhout** [comment]
Should be fixed in Release 0.2.13

**Comment by RichardLindhout** [comment]
Excuse me it's 0.2.14 I forgot to build the updated library in 0.2.13
