### ISSUE TITLE
Having issues with Range Selection

### ISSUE THREAD

**Issue by AbisheekKumar** [web-ridge/react-native-paper-dates#344]
Hello,

I am currently encountering an issue with the Range Date Picker component while using the en-GB locale. When I attempt to select a date range from 2023-10-02 to 2023-10-08, the start date is incorrectly being registered as 2023-10-01. I have followed the implementation guidelines provided in the official documentation.

I would greatly appreciate your assistance in resolving this matter.

Here is my program:

```
import React from "react";
import { View, Text } from "react-native";
import { Button } from 'react-native-paper';
import { enGB, DatePickerModal, registerTranslation } from 'react-native-paper-dates';
import { SafeAreaProvider } from "react-native-safe-area-context";

registerTranslation('en-GB', enGB);

export default function App() {
  const [range, setRange] = React.useState({ startDate: undefined, endDate: undefined });
  const [open, setOpen] = React.useState(false);

   const onDismiss = React.useCallback(() => {
    setOpen(false);
  }, [setOpen]);

 const onConfirm = React.useCallback(
    ({ startDate, endDate }) => {
      setOpen(false);
      setRange({ startDate, endDate });
    },
    [setOpen, setRange]
  );

  return (
    <SafeAreaProvider>
      <View style={{ justifyContent: 'center', flex: 1, alignItems: 'center' }}>
        <Button onPress={() => setOpen(true)} uppercase={false} mode="outlined">
          Pick range
        </Button>
        <DatePickerModal
          locale="en-GB"
          mode="range"
          visible={open}
          onDismiss={onDismiss}
          startDate={range.startDate}
          endDate={range.endDate}
          onConfirm={onConfirm}
        />
      </View>
    </SafeAreaProvider>
  )
}

```
Thank You,

**Comment by AbisheekKumar** [comment]
Hi, Sure I'll provide you the repro

**Comment by brunog2** [comment]
Same issue here. Did you find a workaround?

**Comment by AbisheekKumar** [comment]
> Same issue here. Did you find a workaround?

Hi @brunog2, Not yet, I'm trying to reproduce the issue with minimal example.

**Comment by AbisheekKumar** [comment]
> Hey! Thanks for opening the issue. Can you provide a minimal repro which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.dev](https://snack.expo.dev). If it's not possible to repro it on [snack.expo.dev](https://snack.expo.dev), then you can also provide the repro in a GitHub repository.

Hi, Here is the repro link on snack. I have added some logs in the lines where I am facing issues.
[](https://snack.expo.dev/@abishek_2000/react-native-paper-dates-)

**Comment by AbisheekKumar** [comment]
Hi, Is there any workaround for this issue ?

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by brunog2** [comment]
> Hi, Is there any workaround for this issue ?

After some testing, i realize that the issue doesn't occur with physical device, so the problem only affect development app.

**Comment by AbisheekKumar** [comment]
> > Hi, Is there any workaround for this issue ?
> 
> After some testing, i realize that the issue doesn't occur with physical device, so the problem only affect development app.

Hi @brunog2 that's nice, I'll take a look at it once again. But when I tested with physical device I faced the same issue.
