### ISSUE TITLE
Is it possible to style the modal?

### ISSUE THREAD

**Issue by Demven** [web-ridge/react-native-paper-dates#349]
This is how the modal looks for me now in Web:
<img width="765" alt="image" src="https://github.com/web-ridge/react-native-paper-dates/assets/4939520/c2584e3a-ad4d-4ecc-b0f9-36fa767b3364">

Can I change the colors, backgrounds, borders, spacings, etc?

**Comment by iM-GeeKy** [comment]
Theming is all derived from the parent libraries [theme](https://callstack.github.io/react-native-paper/docs/guides/theming). Outside of these configurations we follow material designs specs for the [date picker](https://m3.material.io/components/date-pickers/overview) and [time picker](https://m3.material.io/components/time-pickers/overview).

**Comment by Demven** [comment]
I'm looking for a Date Picker that can work in both iOS and Web, and can be styled according to my own design, with every element being restyled. And seems like your component is the only one that can work in Web and iOS, but styling it seems very challenging... Thanks for the answer though.
