### ISSUE TITLE
design issue on ipad

### ISSUE THREAD

**Issue by ganesh-papola** [web-ridge/react-native-paper-dates#35]
<img width="376" alt="Screenshot 2021-01-08 at 1 17 09 PM" src="https://user-images.githubusercontent.com/19851598/103988274-d1747c00-51b3-11eb-8eaf-514b1538cf7a.png">
design is not proper on ipads.
gap between days and dates

**Comment by ganesh-papola** [comment]
@RichardLindhout can you check this please

**Comment by RichardLindhout** [comment]
Are you using the latest version? We have fixed some issues regarding ipads etc

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2021-01-08 om 11 32 52](https://user-images.githubusercontent.com/6492229/104005344-43919480-51a5-11eb-823b-9fbfe96fc54e.png)

**Comment by RichardLindhout** [comment]
It was fixed a few days ago with the Autosizer instead of hardcoded width/height of the screen

**Comment by ganesh-papola** [comment]
@RichardLindhout  My bad.
Working perfect now. Thanks

**Comment by RichardLindhout** [comment]
Happy to hear!
