### ISSUE TITLE
iOS statusbar height 

### ISSUE THREAD

**Issue by joeburghard** [web-ridge/react-native-paper-dates#354]
### Current behaviour
Greetings! I'm seeing an issue within iOS devices for `DatePickerModal` where the modal is under the statusbar. The view that's styling the top of the modal to provide space is doing the following.

<img width="456" alt="Screenshot 2023-11-15 at 9 52 46 AM" src="https://github.com/web-ridge/react-native-paper-dates/assets/96442093/77a347c4-27f4-4b23-8713-d13f43e41418">

This works all but for ios. Looking further into react native docs the `StatusBar.currentHeight` is strictly android and returns `undefined` for iOS.
### Expected behaviour
The expected behaviour is the header of `DatePickerModal` should be directly under statusbar without disabling statusbar padding

### How to reproduce?
Using the latest versions of react-native-paper( 5.11.1 ) and react-native-paper-dates( 0.20.04 ) create the react-native-paper-dates-range-picker example from docs and launch through iPhone14 simulator or real device.

### Preview
<img width="348" alt="Screenshot 2023-11-15 at 9 49 02 AM" src="https://github.com/web-ridge/react-native-paper-dates/assets/96442093/d871f7d7-4810-4a7c-b765-671f575a71ad">

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by joeburghard** [comment]
Unfortunately that did not work either. I've found success using
`
  StatusBarManager.getHeight(({ height }: { height: number }) => {
    setIOSHeight(height)
  });
`

**Comment by RichardLindhout** [comment]
I think we need to use react-native-safe-area-context always and not the other solutions.
But it looks like some people do not have correctly configured this library.

When it's configured well it looks like it's now applied 2 two times.
![Scherm­afbeelding 2023-12-07 om 17 47 37](https://github.com/web-ridge/react-native-paper-dates/assets/6492229/d7b8ec6e-b706-4b5e-a587-4dd41ab52ba1)


https://snack.expo.dev/@richardlindhout/react-native-paper-dates-ios-statusbar?platform=android

**Comment by RichardLindhout** [comment]
Also the safe area should be disabled when presentation mode is sheet + color should be better based on same logic as headerBackgroundColor

**Comment by joeburghard** [comment]
@RichardLindhout  Still not getting the desired result. I upgraded my dependencies and tested using the range example in the documentation
```
 "react-native-paper": "^5.10.0",
 "react-native-paper-dates": "^0.18.12",
 "react-native-safe-area-context": "4.5.0"
```
<img width="301" alt="Screenshot 2023-12-20 at 10 01 21 AM" src="https://github.com/web-ridge/react-native-paper-dates/assets/96442093/ffae319a-ea5c-4105-833e-6ebab6882e17">

**Comment by RichardLindhout** [comment]
@joeburghard do you have safe-area-context correctly configured?

**Comment by RichardLindhout** [comment]
<img width="487" alt="Scherm­afbeelding 2023-12-21 om 19 50 08" src="https://github.com/web-ridge/react-native-paper-dates/assets/6492229/ab9ef3d0-1aec-4f75-9f86-34e14a4ef609">
<img width="475" alt="Scherm­afbeelding 2023-12-21 om 19 50 30" src="https://github.com/web-ridge/react-native-paper-dates/assets/6492229/64a34835-cfb3-47db-b996-0bebb4b5f0ab">
<img width="485" alt="Scherm­afbeelding 2023-12-21 om 19 52 37" src="https://github.com/web-ridge/react-native-paper-dates/assets/6492229/8a5002af-0114-47dd-b8b8-b27182608edb">
<img width="460" alt="Scherm­afbeelding 2023-12-21 om 19 52 44" src="https://github.com/web-ridge/react-native-paper-dates/assets/6492229/af2756e6-e5fd-4c35-97a9-a27ff32a28fb">
<img width="475" alt="Scherm­afbeelding 2023-12-21 om 19 52 59" src="https://github.com/web-ridge/react-native-paper-dates/assets/6492229/684928fd-27a2-4777-9b84-64cdda704965">

**Comment by RichardLindhout** [comment]
New release soon avalailable!
