### ISSUE TITLE
Date picker modal appearing ouside safe area

### ISSUE THREAD

**Issue by lfpraca** [web-ridge/react-native-paper-dates#359]
### Current behaviour
When attempting to implement a single date picker, the top of the modal would always appear behind the notification bar on android.

Additionally, the snack itself is not working on adroid, so I was unable to test if that works or not, but I tried to replicate it closely

### Expected behaviour
Stay within the safe area, as it does on iOS using the documentation example

### How to reproduce?
- Implement the example code from https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/single-date-picker

https://github.com/lfpraca/react-native-dates-test

### Preview
![image](https://github.com/web-ridge/react-native-paper-dates/assets/134505289/d9299969-eb89-40a7-991d-7bece0001ef4)

### What have you tried so far?
Moving the SafeAreaProvider to multiple places, removing it altogether; moving and removing PaperProvider; using SafeAreaView; using insets; using portal

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 13
| react-native                | 0.72.6
| react-native-paper    | 5.11.3
| node                            | 20.7.0
| npm                             | 10.1.0

**Comment by SoyDiego** [comment]
@RichardLindhout

**Comment by iM-GeeKy** [comment]
Maybe try `disableStatusBarPadding`. This doesn't seem to be the case on the example in the document. https://snack.expo.dev/@fitzwabs/react-native-paper-dates-single-picker

**Comment by RichardLindhout** [comment]
Should be fixed now. Also use statusBarTranslucent through your android app

**Comment by jmarks-joshua** [comment]
> Maybe try `disableStatusBarPadding`. This doesn't seem to be the case on the example in the document. https://snack.expo.dev/@fitzwabs/react-native-paper-dates-single-picker

The version of react-native-paper-dates on that snack is ^0.11.0 so it's not really a fair assessment on if the current version works. I am very much getting this problem on my app and I've just copy pasted the full example in. Only a very recent version works for me on ios and only an old version works for me on android.
