### ISSUE TITLE
Calendar Background 

### ISSUE THREAD

**Issue by CZEpitech** [web-ridge/react-native-paper-dates#360]
Hello, how can I change the white/grey background of the calendar ?
![Screenshot 2023-12-12 at 11-56-42 Absence](https://github.com/web-ridge/react-native-paper-dates/assets/118726661/ba603804-f6e6-42e9-9468-901e3abda4a5)
Thanks

**Comment by jrichichi** [comment]
It's based off theme styles, so diving into the source code and finding which theme color the background pulls from is probably the way to go.

**Comment by iM-GeeKy** [comment]
@jrichichi Is correct. The color is derived from the paper theme.
