### ISSUE TITLE
renders incorrectly on android 6

### ISSUE THREAD

**Issue by breathingcyborg** [web-ridge/react-native-paper-dates#362]
### Current behavior

I'm using the [official demo](https://snack.expo.dev/@fitzwabs/react-native-paper-dates-input) in the docs, in expo go app. The date picker is not rendering correctly on android 6 device. Have a look at the screenshot to understand what i mean.

### Expected behavior
The date picker input should render correctly on android 6 device. Just like it renders correctly on android 9 device.

### How to reproduce?
1. visit https://snack.expo.dev/@fitzwabs/react-native-paper-dates-input
2. open this demo in expo go app on android 6 device.

### Preview
![Screenshot_20231214-164447](https://github.com/web-ridge/react-native-paper-dates/assets/75165003/da80505f-b322-4b0f-8b9b-2e5348d90453)

### What have you tried so far?
- Wrapped the demo code in paper provider. 
- Changed expo version from 48 to 49

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | 6.0.1
| react-native                | x.x.x
| react-native-paper    | 5.10.0
| react-native-paper-dates| 0.18.12
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | 48.0.0 / 49.0.0

**Comment by RichardLindhout** [comment]
Do you have hermes enabled?

**Comment by thvbb** [comment]
Same on me ~~~
