### ISSUE TITLE
AM/PM Is hardcoded, which is tough when trying to localize.

### ISSUE THREAD

**Issue by Rob117** [web-ridge/react-native-paper-dates#365]
### Current behaviour
AM and PM seem to be [hardcoded into the Timepicker](https://github.com/web-ridge/react-native-paper-dates/blob/8d6791d9e8d1bb10bcc06581efb107faf8b497da/src/Time/TimePicker.tsx#L71)

### Expected behaviour
I'd like for AM and PM be a prop so I can change them, because in Japanese they are 午前 and 午後 and AM/PM is difficult to understand.

### What have you tried so far?
I think at this point the only thing I can do is patch the library file, which is probably not ideals

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by RichardLindhout** [comment]
It should automatically change itself to be 24h if your locale is correct, please give us a snack with your locale and try to find why it does not detect 24h for your locale.

**Comment by RichardLindhout** [comment]
Did you set up your locale?
