### ISSUE TITLE
Icons are missing from Modal Calendar 

### ISSUE THREAD

**Issue by plueondee** [web-ridge/react-native-paper-dates#370]
### Current behaviour

run the app and got the warning 
 Warning: Failed prop type: Invalid prop `name` of value `menu-up` supplied to `Icon`, expected one of ["activity","airplay","alert-circle","alert-octagon","alert-triangle","align-center","align-justify","align-left","align-right","anchor","aperture","archive","arrow-down","arrow-down-circle","arrow-down-left","arrow-down-right","arrow-left","arrow-left-circle","arrow-right","arrow-right-circle","arrow-up","arrow-up-circle","arrow-up-left","arrow-up-right","at-sign","award","bar-chart","bar-chart-2","battery","battery-charging","bell","bell-off","bluetooth","bold","book","book-open","bookmark","box","briefcase","calendar","camera","camera-off","cast","check","check-circle","check-square","chevron-down","chevron-left","chevron-right","chevron-up","chevrons-down","chevrons-left","chevrons-right","chevrons-up","chrome","circle","clipboard","clock","cloud","cloud-drizzle","cloud-lightning","cloud-off","cloud-rain","cloud-snow","code","codepen","codesandbox","coffee","columns","command","compass","copy","corner-down-left","corner-down-right","corner-left-down","corner-left-up","corner-right-down","corner-right-up","corner-up-left","corner-up-right","cpu","credit-card","crop","crosshair","database","delete","disc","divide","divide-circle","divide-square","dollar-sign","download","download-cloud","dribbble","droplet","edit","edit-2","edit-3","external-link","eye","eye-off","facebook","fast-forward","feather","figma","file","file-minus","file-plus","file-text","film","filter","flag","folder","folder-minus","folder-plus","framer","frown","gift","git-branch","git-commit","git-merge","git-pull-request","github","gitlab","globe","grid","hard-drive","hash","headphones","heart","help-circle","hexagon","home","image","inbox","info","instagram","italic","key","layers","layout","life-buoy","link","link-2","linkedin","list","loader","lock","log-in","log-out","mail","map","map-pin","maximize","maximize-2","meh","menu","message-circle","message-square","mic","mic-off","minimize","minimize-2","minus","minus-circle","minus-square","monitor","moon","more-horizontal","more-vertical","mouse-pointer","move","music","navigation","navigation-2","octagon","package","paperclip","pause","pause-circle","pen-tool","percent","phone","phone-call","phone-forwarded","phone-incoming","phone-missed","phone-off","phone-outgoing","pie-chart","play","play-circle","plus","plus-circle","plus-square","pocket","power","printer","radio","refresh-ccw","refresh-cw","repeat","rewind","rotate-ccw","rotate-cw","rss","save","scissors","search","send","server","settings","share","share-2","shield","shield-off","shopping-bag","shopping-cart","shuffle","sidebar","skip-back","skip-forward","slack","slash","sliders","smartphone","smile","speaker","square","star","stop-circle","sun","sunrise","sunset","tablet","tag","target","terminal","thermometer","thumbs-down","thumbs-up","toggle-left","toggle-right","tool","trash","trash-2","trello","trending-down","trending-up","triangle","truck","tv","twitch","twitter","type","umbrella","underline","unlock","upload","upload-cloud","user","user-check","user-minus","user-plus","user-x","users","video","video-off","voicemail","volume","volume-1","volume-2","volume-x","watch","wifi","wifi-off","wind","x","x-circle","x-octagon","x-square","youtube","zap","zap-off","zoom-in","zoom-out"].

### Expected behaviour

Icons should show up

### How to reproduce?

run the app and click the calendar icon

### Preview

![Simulator Screenshot - iPhone 15 Pro - 2024-02-13 at 15 18 05](https://github.com/web-ridge/react-native-paper-dates/assets/108423364/6433adb0-ec91-4f77-922f-58a33a755762)

### What have you tried so far?

upgrade react native papers and react native to the latest

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                |  iphone 15 (17.2)
| android                        | x
| react-native                | "0.73.4"
| react-native-paper    | "^5.12.3"
| node                            | ">=18"
| npm or yarn                | yarn
| expo sdk                     | x.x.x

**Comment by FloKla** [comment]
I have exactly the same issue since updating to expo 50.

Seems to be caused/releated by/to this: https://github.com/callstack/react-native-paper/issues/4295

**Comment by phabiulla** [comment]
Same issue here! I choose to use the **Feather** icons and seems not all the icons are configurable.
I'm having issues specially with the `menu-down/menu-up` icons

![WhatsApp Image 2024-03-10 at 20 56 42](https://github.com/web-ridge/react-native-paper-dates/assets/68568193/8cc4f654-59af-4532-a176-5242d197fc93)
<img width="801" alt="Screenshot 2024-03-10 at 20 58 05" src="https://github.com/web-ridge/react-native-paper-dates/assets/68568193/c1fbfe1f-4671-46a4-b92f-3701550deeee">

**Comment by zorgoluis** [comment]
> ¡El mismo problema aquí! Elijo usar los íconos de **pluma** y parece que no todos los íconos son configurables. Tengo problemas, especialmente con los iconos.`menu-down/menu-up`
> 
> <img alt="Captura de pantalla 2024-03-10 en 20 58 05" width="801" src="https://private-user-images.githubusercontent.com/68568193/311543851-c1fbfe1f-4671-46a4-b92f-3701550deeee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzA4NDMsIm5iZiI6MTcxMDk3MDU0MywicGF0aCI6Ii82ODU2ODE5My8zMTE1NDM4NTEtYzFmYmZlMWYtNDY3MS00NmE0LWI5MmYtMzcwMTU1MGRlZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIxMzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODM4MWNhMGQ1NWNiZDg4MGExNWY0ZTJmZThkNmM2MTRiZmQ1NWY0ZGRiYzFhY2NkOGNjMTEzYWViMTMxYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-dmHz9CnCsXRBASmfpyZn8RRMea39-gzOhvYbMMT3YE"> <img alt="Captura de pantalla 2024-03-10 a las 20 59 43" width="275" src="https://private-user-images.githubusercontent.com/68568193/311543922-c61c1923-63da-41b6-8850-8b0d1261ea8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzA4NDMsIm5iZiI6MTcxMDk3MDU0MywicGF0aCI6Ii82ODU2ODE5My8zMTE1NDM5MjItYzYxYzE5MjMtNjNkYS00MWI2LTg4NTAtOGIwZDEyNjFlYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIxMzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZTM0MWNkMGY3YjAyOWQzMTk4NTcyMmNlZGVmYTM4ZjRlZDgzODg3MmJhYWU1NzRlYTk3NzNjNTY0NTJiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_DEOY9gnO6A8zUVVie3VVJOXdiLzP9HMkz8TeV7epE">

solo esta para MaterialCommunityIcons

**Comment by RichardLindhout** [comment]
I currently overwrite the icons with the react-native-paper settings on the ThemeProvider there you can replace all kind of icons with custom ones

**Comment by RichardLindhout** [comment]
PR for this is welcome
