### ISSUE TITLE
Allow setting a specific minute intervals on time picker 

### ISSUE THREAD

**Issue by minuz** [web-ridge/react-native-paper-dates#376]
**Is your feature request related to a problem? Please describe.**
My team is building a timesheet application and we have some use cases where we don't want to allow our users to pick precise minutes. In certain cases, we need to use 30 minutes increments and others 5 minutes and others will full precision. At the moment, it does seems like we have a way to control this.

**Describe the solution you'd like**
An optional prop such as `minuteInterval?: number` where the number would be used to display the time increments on the clock and only allow the user to select within that range. Should default to 1 as it currently is. 

**Describe alternatives you've considered**
I haven't found any prop that could control this. It doesn't seems like we can override or extend the component to achieve this. If there is, please point me to the right direction!

**Comment by iM-GeeKy** [comment]
PRs are welcome!
