### ISSUE TITLE
Anybody else getting this ? 

### ISSUE THREAD

**Issue by FutureIronman7** [web-ridge/react-native-paper-dates#38]
TypeError: onConfirm is not a function. (In 'onConfirm({
          startDate: state.startDate,
          endDate: state.endDate
        })', 'onConfirm' is undefined)

 My  code;

import React, { Component , useState} from "react";
import { View, Text, StyleSheet, Button} from "react-native";
// import { Button } from 'react-native-paper'
import { DatePickerModal } from 'react-native-paper-dates'
import { onChange } from "react-native-reanimated";

export default class CalendarScreen extends Component {

  CALENDAR= ()=>{

    console.log("mike")
    // setVisible(true)
    [visible, setVisible] = React.useState(false).bind(this)
    onDismiss = React.useCallback(() => {
      setVisible(false)
    }, [setVisible]).bind(this)
  
      onChange = React.useCallback(({ startDate, endDate }) => {
      setVisible(false).bind(this)
      console.log({ startDate, endDate })

    
    }, [])

  }

  render(){

    return (
      <View style= {styles.container} >
      <Text> CalendarScreen</Text>

      <DatePickerModal
              mode="range"
              visible={this.CALENDAR.visible}
              onDismiss={this.CALENDAR.onDismiss}
              startDate={undefined}
              endDate={undefined}
              //onConfirm={this.CALENDAR.onConfirm}
              onChange= {onChange}
              saveLabel="Save" // optional
              label="Select period" // optional
              startLabel="From" // optional
              endLabel="To" // optional
              animationType="slide" // optional, default is slide on ios/android and none on web
              locale={'en'} // optional, default is automically detected by your system
        
      />
      <Button title="Pick Range" onPress={this.CALENDAR} /> 
        

    </View>
    
   
    )
  } 

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    width:"100%"
    
  }
});

**Comment by FutureIronman7** [comment]
posted in wrong place, please ignore

**Comment by RichardLindhout** [comment]
It's a typescript error, you should provide a function with nothing in return
