### ISSUE TITLE
Multiple Range Latency

### ISSUE THREAD

**Issue by iM-GeeKy** [web-ridge/react-native-paper-dates#383]
### Current behaviour

The multiple dates picker appears to gradually get slower the more dates that are selected. This seems to be more noticeable on iOS as opposed to Android and Web.

### Expected behaviour

The dates should be selected in a reasonable time.

### How to reproduce?

https://snack.expo.dev/@fitzwabs/react-native-paper-dates-multiple-picker or it also seen in the repositories example app.

### Preview
https://github.com/web-ridge/react-native-paper-dates/assets/7604441/b1e2d30d-81ad-48ad-ade3-66de8cd2b26f

### What have you tried so far?

@RichardLindhout I haven't looked into this yet, but I'm assuming it is performing a lot of re-renders. Perhaps you have more insight off the top of your head.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.4
| android                        | 14.0
| react-native                | 0.73.6
| react-native-paper    | 5.12.3
| node                            | 20.10.0
| npm or yarn                | yarn
| expo sdk                     | 50.0.17

**Comment by iM-GeeKy** [comment]
@RichardLindhout Do you have any initial thoughts?

**Comment by iM-GeeKy** [comment]
@RichardLindhout Do you have any insight into this? I'm going to try to fix this in the next couple of weeks as it's affecting my app and any ideas you might have will serve as a good starting point.

**Comment by RichardLindhout** [comment]
Hey! It is probably because array will re-render everything because some property is not stable 'enough' so something triggers the day to re-render. I thought we only used simple promps in day to prevent this but maybe something else is slow

**Comment by RichardLindhout** [comment]
Do they days also re-render?

**Comment by iM-GeeKy** [comment]
I'll have to put some logs in. I just know it only happens on iOS and the rendering of grid gets increasingly slower, but perhaps the days is the real culprit.

**Comment by iM-GeeKy** [comment]
It appears its rendering all the days again for each month, so I'll have to explore how we can avoid that from happening.

**Comment by iM-GeeKy** [comment]
Any ideas? It seems strange it only happens on iOS...
