### ISSUE TITLE
Show year in selected date label

### ISSUE THREAD

**Issue by oldo** [web-ridge/react-native-paper-dates#384]
Is there any way to also show the year in the selected date label at top left of the component?
I am only able to see day and month. For clarity it would be great to be able to see year as well.

![image](https://github.com/web-ridge/react-native-paper-dates/assets/4557648/64bbfea4-bf54-48a8-8f40-e2a5a6b95f4e)

**Comment by iM-GeeKy** [comment]
Hi @oldo, it doesn't appear that adheres to the [guidelines](https://m3.material.io/components/date-pickers/guidelines) and seeing that the year is below it, that would be my guess for why Google did it the way they did 🤷🏼‍♂️.

**Comment by oldo** [comment]
No worries, thanks for responding @iM-GeeKy :-)

**Comment by iM-GeeKy** [comment]
Yeah, sorry for the delayed response. @RichardLindhout might have a different opinion, so I'll let him have the ultimate say 👍🏻
