### ISSUE TITLE
Dialog styling does not respect theme roundness value

### ISSUE THREAD

**Issue by Absor** [web-ridge/react-native-paper-dates#386]
### Current behaviour
Dialog has rounded corners even if you specify `roundness: 0` in paper theme.

### Expected behaviour
Dialog to not have rounded corners when roundness is set to zero.

### How to reproduce?
Create a theme with roundness set to zero and provide that to PaperProvider. Use time picker inside the provider and see that the corners are rounded.

### Preview
-

### What have you tried so far?
This is just wrong in current implementation. Roundness is not even considered.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by iM-GeeKy** [comment]
PRs are welcome!
