### ISSUE TITLE
Cannot disable save button or set saveLabelDisabled true when invalid date is entered?

### ISSUE THREAD

**Issue by suniltakorsvp** [web-ridge/react-native-paper-dates#388]
### How to disable save button or set saveLabelDisabled true when invalid date is entered?

I'm trying to disable 'Save' button or set saveLabelDisabled true when invalid date is entered.

Let me know if someone already faced this issue and already fixed.

![Disable Save button](https://github.com/web-ridge/react-native-paper-dates/assets/163214975/e8c22cae-d219-4811-ac68-094071c6dbbe)

**Comment by RichardLindhout** [comment]
@suniltakorsvp I will accept a PR which will not send the in onConfirm. I don't want to disable buttons it is bad UX.
https://uxdworld.com/2024/01/29/disabled-buttons-ux/#:~:text=Design%20is%20communication%20and%20disabled,while%20interacting%20with%20an%20interface.
