### ISSUE TITLE
DatePickerInput crashed with initial value

### ISSUE THREAD

**Issue by AlejandroRM-DEV** [web-ridge/react-native-paper-dates#390]
### Current behaviour
When you tap the icon to open the modal, the application crashes.

### Expected behaviour
Open the modal to select the date.

### How to reproduce?
```
export function DatePicker({ control, name, rules, style, ...rest }) {
  return (
    <Controller
      control={control}
      name={name}
      rules={rules}
      render={({ field: { onChange, value } }) => (
        <DatePickerInput
          locale={i18n.locale}
          label=""
          iconSize={16}
          inputMode="start"
          style={[styles.datePicker, style]}
          mode="outlined"
          dense
          withDateFormatInLabel={false}
          onChange={(d) => onChange(d)}
          value={value}
          {...rest}
        />
      )}
    />
  );
}
```

### Preview
![Simulator Screenshot - iPhone 15 Pro Max - 2024-05-21 at 23 52 17](https://github.com/web-ridge/react-native-paper-dates/assets/8054357/9cc738ad-85c7-429a-9259-b95b3b068584)

### What have you tried so far?
If I do not pass the value property, the modal is displayed.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.2
| react-native                | 0.74.1
| react-native-paper    | ^5.12.3
| expo sdk                     | ^51.0.8

**Comment by iM-GeeKy** [comment]
Working examples can be found in the [docs](https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/input-date-picker). If you suspect this is still a bug feel free to open a PR!

**Comment by AlejandroRM-DEV** [comment]
Thanks for the reply, I finally realized that I was passing a dayjs object instead of Date as a value
