### ISSUE TITLE
DatePickerModal jump wildly when landscape in IOS device

### ISSUE THREAD

**Issue by UIT19521334** [web-ridge/react-native-paper-dates#391]
### Current behaviour
The DatePickerModal component jumps wildly when the device is in landscape mode on iOS using react-native-paper-dates.

### Expected behaviour
I expect the DatePickerModal component to remain stable and not jump when the device is switched to landscape mode on iOS.

### How to reproduce?
1. Open the app on an iOS device.
2. Navigate to a screen where the DatePickerModal component is used.
3. Rotate the device to landscape mode.
4. Observe the DatePickerModal jumping wildly

### Preview

https://github.com/web-ridge/react-native-paper-dates/assets/67258104/8da4c8ac-6fe3-45f7-90c0-5c14447f2745

### What have you tried so far?
- Install version 0.22.9
- wrap in to View have width = deviceWidth

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 17.4
| android                        | x.x.x
| react-native                | 0.73.1
| react-native-paper    | 5.11.6
| node                            | 21.7.2
| npm or yarn                | yarn

**Comment by iM-GeeKy** [comment]
This appears to be linked to this [pull request](https://github.com/web-ridge/react-native-paper-dates/pull/368) feel free to try it out and fix the PR if it is a proper solution!

**Comment by UIT19521334** [comment]
Thank you, you saved my time. I am very happy to have fixed it in the node module with the following comment. I hope this bug will be fixed in the next version.

**Comment by iM-GeeKy** [comment]
> Thank you, you saved my time. I am very happy to have fixed it in the node module with the following comment. I hope this bug will be fixed in the next version.

I'll test it and try to get it merged in the next version. Thanks!

**Comment by iM-GeeKy** [comment]
![simulator_screenshot_5584DDFF-9BDE-450E-B193-CD5EFE6FF09E](https://github.com/web-ridge/react-native-paper-dates/assets/7604441/fec9f57c-79a7-47e3-bb0f-24cd8c13e28b)

@UIT19521334 Did the proposed fix, make the calendar look like this? It seems to fix the jump, but doesn't appear to be fully responsive, so it needs some work still apparently.
