### ISSUE TITLE
Render Error for DatePickerInput component: "Check the render method of 'Month'"

### ISSUE THREAD

**Issue by kalyncoose** [web-ridge/react-native-paper-dates#392]
**Issue:**
`DatePickerInput` component starts to render but crashes when attempting to render the `Month` child component inside the 'Calendar'.

![image](https://github.com/web-ridge/react-native-paper-dates/assets/65800415/fecfe6cc-5da0-46a4-bdbd-cd3ac67a35bd)

**Resolution:**
We noticed the `peerDependencies` for `react-native-paper` is an asterisk `*` which is a bad idea for ensuring compatibility and letting end users know what version they should be using at a minimum. We upgraded `react-native-paper` from `5.3.1` to `5.12.3` which resolved the rendering issue - now the `DatePickerInput` can fully render and load the calendar (albeit pretty slow in a debug mode app). Side note: when upgrading to the new `react-native-paper` version we had to change an import of `Provider` to `PaperProvider` for `react-native-paper`.

https://github.com/web-ridge/react-native-paper-dates/blob/9da295e919c3b4c68ee01b3770dda6646a34b873/package.json#L87

**Suggestion:**
Please put down actual version numbers instead of asterisks for the peer dependencies of this package.

**Comment by chamellion** [comment]
Same issue here

**Comment by onebigdoor** [comment]
i got this error and resolved it by updating to the latest version of `react-native-paper` (note that it's a separate package from `react-native-paper-dates`)
