### ISSUE TITLE
DatePickerInput ~ setModalVisible exposition in ref

### ISSUE THREAD

**Issue by Izocel** [web-ridge/react-native-paper-dates#393]
**Is your feature request related to a problem? Please describe.**
No bug, but very usefull feature.

**Describe the solution you'd like**
Could you guys expose the modal visibily in the inputs ref ?

```
  function setModalVisible(value:boolean = false) {
    setVisible(value);
    return value;
  }

  React.useImperativeHandle(ref, () => ({
    setModalVisible
  }));
  ```

**Comment by iM-GeeKy** [comment]
PRs are welcome!
