### ISSUE TITLE
Selecting year does not work in single date picker

### ISSUE THREAD

**Issue by RichardLindhout** [web-ridge/react-native-paper-dates#4]

**Comment by RichardLindhout** [comment]
This is almost done in development but still has a strange bug if you go next year it and then select others years it will bug

**Comment by yogieeka** [comment]
yes me to

**Comment by RichardLindhout** [comment]
I think it only does not work in the web version at the moment. Can you confirm? And are you on the latest version?

**Comment by RichardLindhout** [comment]
This is fixed in v0.2.10
