### ISSUE TITLE
Getting error undefined is not a constructor (evaluating 'new Intl.Locale(locale)')

### ISSUE THREAD

**Issue by shreesha** [web-ridge/react-native-paper-dates#40]
Hello Team,
Am getting error undefined is not a constructor (evaluating 'new Intl.Locale(locale)') when I run the react-native run-android.
I have run 
yarn add react-native-paper-dates
and
yarn add react-native-localize @formatjs/intl-pluralrules @formatjs/intl-getcanonicallocales @formatjs/intl-listformat @formatjs/intl-displaynames @formatjs/intl-locale @formatjs/intl-datetimeformat @formatjs/intl-numberformat @formatjs/intl-relativetimeformat

and My jcsFlavor is:   jscFlavor = 'org.webkit:android-jsc:+'

my index.js is 

===============================
import { AppRegistry } from 'react-native';
import App from './src/app';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);

// //Check for android platform and hermes enabled in order to include polyfills
const isAndroid = require('react-native').Platform.OS === 'android';
const isHermesEnabled = !!global.HermesInternal;

// //If hermises enabled or if it is android include polifills
// //this is required for react-native-papaer-dates
if (isHermesEnabled || isAndroid) {
  require('@formatjs/intl-getcanonicallocales/polyfill');

  require('@formatjs/intl-pluralrules/polyfill');
  require('@formatjs/intl-pluralrules/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

  require('@formatjs/intl-relativetimeformat/polyfill');
  require('@formatjs/intl-relativetimeformat/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

  require('@formatjs/intl-listformat/polyfill');
  require('@formatjs/intl-listformat/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

  require('@formatjs/intl-displaynames/polyfill');
  require('@formatjs/intl-displaynames/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

  require('@formatjs/intl-numberformat/polyfill');
  require('@formatjs/intl-numberformat/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

  require('@formatjs/intl-datetimeformat/polyfill');
  require('@formatjs/intl-datetimeformat/locale-data/en.js'); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

  require('@formatjs/intl-datetimeformat/add-golden-tz.js');

  require('@formatjs/intl-locale/polyfill');

//   //ToDo: need to check if setting timezone is needed
//   // https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone
  let RNLocalize = require('react-native-localize');
  if ('__setDefaultTimeZone' in Intl.DateTimeFormat) {
    Intl.DateTimeFormat.__setDefaultTimeZone(RNLocalize.getTimeZone());
  }
}
================================
Please help solve the problem.

If i do not change the index.js as mentioned in the readme document, i get an error at the component where i use the picker as: ReferenceError: Can't find variable: Intl

**Comment by RichardLindhout** [comment]
Yes we had the wrong instructions in the past, I think you have the same issue as described here: https://github.com/web-ridge/react-native-paper-dates/issues/33

Please read the instructions on the latest release, it will probably fix your issue!
https://github.com/web-ridge/react-native-paper-dates/releases/tag/v0.2.15

**Comment by RichardLindhout** [comment]
It also can be a good idea to make an index.android.js file with the imports and a index.js without the polyfills. because formatjs will be imported on iOS too but is not needed there.

**Comment by shreesha** [comment]
Thanks for quick response. It solved the problem.

**Comment by RichardLindhout** [comment]
👌🥳
