### ISSUE TITLE
No Icons in 'DatePickerInput' modal when using 'Material Design 2'

### ISSUE THREAD

**Issue by gengurke** [web-ridge/react-native-paper-dates#400]
### Current behavior
Since quite a while (around updating to expo 50) the icons are missing from the `DatePickerInput` modal. 
I thought I just configured something wrong until I check the official example / demo on https://www.reactnativepaperdates.com/ which has the same issue, when using `Material Design 2`. 

How can this be fixed, since this seems to affect everyone?

### Expected behavior
- Icons should show up

### How to reproduce?
- Update to expo 50/51

### Preview
Problem on the official demo Page: https://www.reactnativepaperdates.com/
![image](https://github.com/web-ridge/react-native-paper-dates/assets/15369406/955c52d5-5d28-4072-ab1e-67f5446af239)
![image](https://github.com/web-ridge/react-native-paper-dates/assets/15369406/b9bad8c2-5e20-46a4-9d0d-67a9aed985ec)

### What have you tried so far?
- Only downgrading expo worked so far, but that is not an option

Thank you in advance

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by iM-GeeKy** [comment]
The example app now has icons for Expo 50/51.
