### ISSUE TITLE
Button style is wrong at web 

### ISSUE THREAD

**Issue by Coolister-Ye** [web-ridge/react-native-paper-dates#407]
### Current behaviour
The button style is wrong at web. It should be a circle around the date, while it render as a line. However, I also test it at ISO, it work correctly. I cannot figure out why.

### How to reproduce?

I put the demo code into a component.

```
import React from "react";
import { View, Text } from "react-native";
import { Button } from 'react-native-paper';
import { DatePickerModal } from 'react-native-paper-dates';
import { SafeAreaProvider } from "react-native-safe-area-context";
import { enGB, registerTranslation } from 'react-native-paper-dates'
registerTranslation('en-GB', enGB)


export default function DatePicker({ }) {

    const [date, setDate] = React.useState(undefined);
    const [open, setOpen] = React.useState(false);

    const onDismissSingle = React.useCallback(() => {
        setOpen(false);
    }, [setOpen]);

    const onConfirmSingle = React.useCallback(
        (params) => {
            setOpen(false);
            setDate(params.date);
        },
        [setOpen, setDate]
    );

    return (
        <SafeAreaProvider>
            <View style={{ justifyContent: 'center', flex: 1, alignItems: 'center' }}>
                <Button onPress={() => setOpen(true)} uppercase={false} mode="outlined">
                    Pick single date
                </Button>
                <DatePickerModal
                    locale="en-GB"
                    mode="single"
                    visible={open}
                    onDismiss={onDismissSingle}
                    date={date}
                    onConfirm={onConfirmSingle}
                />
            </View>
        </SafeAreaProvider>
    );
}
```
And then I just impor it in App.js. I'm using nativewind to do some `styling.`

```
<SafeAreaView className="pt-10 h-screen bg-slate-200">
      <DatePicker />
</SafeAreaView>
```

### Preview
<img width="613" alt="截屏2024-07-16 21 32 06" src="https://github.com/user-attachments/assets/46a4b30d-edb8-41d3-9a46-dc1349609d65">

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | "0.74.2"
| react-native-paper    | "^5.12.3"
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | "~51.0.17"

**Comment by Coolister-Ye** [comment]
I'm trying to create a snack repo, but it failed because I'm using expo router. The snack require an App.js file at the root level of the project. And then I tried to copy and paste the code into App.js, which worked fine on snack and rendered correctly. You can check on [this snack](https://snack.expo.dev/@coolister/6ca922). It seems the problem maybe related to the expo router. You can also check all my project code in this Github [repository](https://github.com/Coolister-Ye/sea-saw.git). Basically, I'm just using the expo router template to create the project and added a new tab under './app/(tabs)/sea.tsx'. The new tab will import and use DatePickerModal component. You may need to clone this project to local and run `npx expo start -c` to reproduce the problem.

The main code is as below.

```
import React from 'react';
import { View } from 'react-native';
import { Button } from 'react-native-paper';
import { DatePickerModal } from 'react-native-paper-dates';
import { SafeAreaProvider } from 'react-native-safe-area-context';

export default function SeaScreen() {

    const [date, setDate] = React.useState(undefined);
    const [open, setOpen] = React.useState(false);

    const onDismissSingle = React.useCallback(() => {
        setOpen(false);
    }, [setOpen]);

    const onConfirmSingle = React.useCallback(
        (params) => {
            setOpen(false);
            setDate(params.date);
        },
        [setOpen, setDate]
    );

    return (
        <SafeAreaProvider>
            <View style={{ justifyContent: 'center', flex: 1, alignItems: 'center' }}>
                <Button onPress={() => setOpen(true)} uppercase={false} mode="outlined">
                    Pick single date
                </Button>
                <DatePickerModal
                    locale="en-GB"
                    mode="single"
                    visible={open}
                    onDismiss={onDismissSingle}
                    date={date}
                    onConfirm={onConfirmSingle}
                />
            </View>
        </SafeAreaProvider>
    );
}
```

**Comment by iM-GeeKy** [comment]
@Coolister-Ye The [web examples in the documentation](https://web-ridge.github.io/react-native-paper-dates/docs/category/date-picker) and [example app](https://www.reactnativepaperdates.com/) don't seem to exhibit this behavior. I'm also using the latest `expo-router` on a personal project and don't see this issue with the latest version of `react-native-paper-dates` on web.

**Comment by rdfurman** [comment]
I checked out @Coolister-Ye's example project and confirmed it is exhibiting the described behavior. This is in addition to the issue showing up in our own project. Perhaps it has something to using the Tabs layout?
