### ISSUE TITLE
<TimePicker hours={24} /> shows 12:00PM is this intented?

### ISSUE THREAD

**Issue by dviluk** [web-ridge/react-native-paper-dates#41]
When I pass the prop `hours={24}` the `<TimePicker  />` shows 12:00PM, i think it should be 12:00AM, right? Or is this the intended behavior?

**Comment by RichardLindhout** [comment]
AM is 00:00 to 12 o clock in the morning which is AM
PM is 12:00 to 24:00 o clock in the evening.

So 24 is correct to show 12:00 pm (which is 24:00)
If you don't want am/pm but 24 hours digital time you can override the locale

**Comment by dviluk** [comment]
I understand. Thanks
