### ISSUE TITLE
Icon typing doesn't match react-native-paper's underlying type

### ISSUE THREAD

**Issue by MikkoSteerpath** [web-ridge/react-native-paper-dates#411]
**Is your feature request related to a problem? Please describe.**
In for example `HeaderPickProps`, the `closeIcon` type is `string`, however this gets eventually passed to Appbar.Action's icon property which has the type `IconSource`. 

**Describe the solution you'd like**
I wish the icon properties in react-native-paper-dates would also be typed as `IconSource` rather than string, to match react-native-paper's type.

**Describe alternatives you've considered**
Currently I'm just casting my IconSource generator method to a string, knowing it all works out.

**Comment by iM-GeeKy** [comment]
PRs are welcome!
