### ISSUE TITLE
Typing time from keyboard displays random minutes after selection, when I type 0 in minutes

### ISSUE THREAD

**Issue by suprith7771** [web-ridge/react-native-paper-dates#412]
### Current behaviour
Typing time from keyboard displays random minutes after selection, when I type 0 in minutes
Like typing, 9 in hour is fine, 
00 in minutes is fine
0 in minutes appends random trailing number.

### Expected behaviour
0 minutes should take 00 minutes in selected time

### How to reproduce?
running it in android platform, or android web ..
  ```
      <TimePickerModal
          use24HourClock={false}
          visible={modalVisible}
          onDismiss={toggleModal}
          onConfirm={(selectedDate) => {
            console.log(selectedDate);
            setSelectedTime(moment(selectedDate).format('HH:mm:ss.SSS[Z]'));
            toggleModal();
          }}
          hours={selectedTime ? moment(selectedTime).hours() : moment().hours()}
          minutes={
            selectedTime ? moment(selectedTime).minutes() : moment().minutes()
          }
        />
```
Is the module usage with my random data/entries

### Preview
(<img width="480" alt="Screenshot 2024-07-31 at 12 41 57 PM" src="https://github.com/user-attachments/assets/74d725ed-e285-4d1b-9264-4c97aafe545e">))

### What have you tried so far?
Tried with different times

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.73.6
| react-native-paper    | 0.20.5
| node                            | 20
| npm or yarn                | x.x.x
| expo sdk                     | 50.0.15

**Comment by iM-GeeKy** [comment]
PRs are welcome!
