### ISSUE TITLE
AM , PM time conversion is wrong, suppose I say 12:30 PM it converts it to 24: 30 which is wrong.. it should display it as 12:30 PM only

### ISSUE THREAD

**Issue by vichi100** [web-ridge/react-native-paper-dates#42]

**Comment by RichardLindhout** [comment]
Please provide more information on why you think this is wrong, I'll reopen the issue then :)

**Comment by prankymat** [comment]
I'm in GMT+8 timezone, when I select 12:00 am in the time picker, it returns `2021-03-27T04:00:00.000Z` (12:00 pm), then when I select 12:00 pm, it returns `2021-03-26T16:00:00.000Z` (12:00 am).

**Comment by RichardLindhout** [comment]
But the time picker only returns hours+minutes?
