### ISSUE TITLE
Select Date and Cancel Not Clickable on IOS - View not in SafeArea

### ISSUE THREAD

**Issue by knightmate** [web-ridge/react-native-paper-dates#424]
### Current behaviour
On the iOS platform, the "Select Date" and "Cancel" icons are appearing in the top bar and are not clickable

### Expected behaviour
On the iOS platform, the "Select Date" and "Cancel" icons  should be under SafeArea View 

### How to reproduce?
Run the App on IOS and Open Calendar Modal

### Preview
![Screenshot 2024-09-10 at 1 32 25 PM](https://github.com/user-attachments/assets/cd6a8a3e-8926-497d-91c5-1516948f1f33)

### What have you tried so far?
I have fixed this by giving Maring from top,
 modalRoot: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginTop:Platform.OS==="ios"?40:0
  },
### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 12
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by iM-GeeKy** [comment]
Here is a working example with `SafeAreaProvider` https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/single-date-picker

**Comment by knightmate** [comment]
@iM-GeeKy 
<SafeAreaProvider>
      <TouchableOpacity onPress={toggleModal}>
        <InputField
          editable={false}
          textColor="#0B0A14"
          value={
            modeLocal === "single"
              ? formatDateForDisplayingInputValue(startDate)
              : `${formatDateForDisplayingInputValue(startDate)} - ${formatDateForDisplayingInputValue(endDate)}`
          }
          disableIconClick={true}
          icon={() => (
            <AppIcon
              name="calendar"
              onPress={toggleModal}
              size={24}
              color="#236EF9"
            />
          )}
          direction="right"
          customTextStyle={{fontSize: 16, fontWeight: "400"}}
        />
      </TouchableOpacity>
      <PaperProvider theme={theme}>
        <DatePickerModal
          mode={modeLocal as any}
          saveLabel={"Save"}
          theme={{color: "red"}}
          validRange={{
            endDate: new Date(
              new Date().getFullYear(),
              new Date().getMonth(),
              new Date().getDate()
            ) // optional
          }}
          maxDate={new Date()}
          visible={isModalVisible}
          onDismiss={toggleModal}
          label="Select Date"
          onConfirm={
            modeLocal === "single"
              ? handleConfirmDateSingle
              : handleConfirmDateRange
          }
          {...(rest as any)}
          /** any is used becase Library typescript has some issue */
        />
      </PaperProvider>
    </SafeAreaProvider>
    here is my code

**Comment by knightmate** [comment]
@iM-GeeKy Is this working for you?
