### ISSUE TITLE
Custom icons (Ionicons) break calendar navigation icons (chevron left/right, menu up/down)

### ISSUE THREAD

**Issue by oussamakh96** [web-ridge/react-native-paper-dates#425]
Hello everyone,

I'm using the icon parameter from react-native-paper to change the default icons to Ionicons like this:

`<PaperProvider
  settings={{
    icon: (props) => <Ionicons {...props} />,
  }}
  theme={AppTheme}
>
`
The icons work across the app, but in the react-native-paper-dates calendar component, the chevron icons for left/right navigation, and the menu up/down icons, are not functioning. They do not render correctly.

I would like to continue using Ionicons for the entire app but also need the calendar icons to work properly. Is there a way to customize the calendar icons or ensure that the navigation icons work with a custom icon set?

Thank you for your help!

**Comment by RichardLindhout** [comment]
Hey yeah I would make a component CustomIonicIcon and log which items are used for icons. Then return their IonicIcon variant

**Comment by oussamakh96** [comment]
Thanks for your response @RichardLindhout Waiting for new pull 😄
