### ISSUE TITLE
Overlaying when editing 

### ISSUE THREAD

**Issue by Sri-Klockmate** [web-ridge/react-native-paper-dates#429]
### Current behaviour

Once we are selecting the date then we want to edit that again when open it is showing multiple layers

### Expected behaviour

it should be clear as using initially only 

### How to reproduce?

select a date display it and click on that again  its overlaying with mutliple things

### Preview

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-25 at 12 25 26](https://github.com/user-attachments/assets/3beee1ff-7243-40a3-8840-83cf48b1beb8)

### What have you tried so far?

handled the date object thatsall

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by RichardLindhout** [comment]
New architecture? Can you provide a snack

**Comment by Sri-Klockmate** [comment]
It was my mistake closing this issue now
