### ISSUE TITLE
Multiple date support

### ISSUE THREAD

**Issue by nandorojo** [web-ridge/react-native-paper-dates#43]
![image](https://user-images.githubusercontent.com/13172299/107966935-83088900-6f7a-11eb-9d55-879070095e9f.png)

Hey @RichardLindhout! Awesome library. Is there a way to select multiple dates like the screenshot above?

**Comment by RichardLindhout** [comment]
Not yet but I think we should add it, but I'm really short on time a.t.m. but I'm currently building some projects related to dates so maybe within 6 months I will add it.

Ofcourse a PR would also be greatly appreaciated!

**Comment by nandorojo** [comment]
Got it, if I were to work on this would you be open to merging? Seems like it would just take an array of year-month-day strings and display them in a list next to / below the calendar.

The normal calendar picker would probably need to be edited to receive an array of dates, in addition to a single date. 

Does that sound good to you? If so, I can take a look tomorrow!

**Comment by nandorojo** [comment]
Opened PR that solves this at #44

**Comment by RichardLindhout** [comment]
Released in 0.3.0! https://github.com/web-ridge/react-native-paper-dates/releases/tag/v0.3.0
