### ISSUE TITLE
It would have been nice if we could use it without react native paper...

### ISSUE THREAD

**Issue by kaneki666** [web-ridge/react-native-paper-dates#46]
i used to use third party libray like react-native-paper...but these makes app bigger so i have started using only react native component...but i like this library...can we use it without react-naive paper

**Comment by RichardLindhout** [comment]
I know, it would be nice if react-native-paper did remove the dependency on react-native-vector icons it would be smaller.
That being said I think I will keep react-native-paper. Feel free to fork but we're using react-native-paper so it will be a lot of work for us to maintain a different application.
