### ISSUE TITLE
Disable/blur old dates

### ISSUE THREAD

**Issue by nandorojo** [web-ridge/react-native-paper-dates#48]
It would be nice to have a boolean that doesn't allow you to click dates before today (i.e. a `minDate: new Date()`). It could then reduce the opacity of the hidden dates, so users know not to click them.

**Comment by nandorojo** [comment]
I think a good strategy could be to use the `validRange` API from FullCalendar: https://fullcalendar.io/docs/validRange

```js
const validRange = {
  start: '2020-05-01', // optional
  end: '2020-08-01' // optional
}
```

**Comment by nandorojo** [comment]
Opened a PR to close this at #49.

CC @RichardLindhout 

Thanks!

**Comment by RichardLindhout** [comment]
Ok perfect! Thank you a lot I have some feedback but looking great so far
