### ISSUE TITLE
Can't find variable: Intl

### ISSUE THREAD

**Issue by andy-io** [web-ridge/react-native-paper-dates#55]
Hi there,

howdy ? thanks for the wonderful library.
Just landed up with this issue when running the library with a date picker (first example in readme doc).
Can't find variable: Intl (running in a react native android app)
Error shows up in this line. Looks like react native doesnt recognize the standard js libraries like a browser does.
https://github.com/web-ridge/react-native-paper-dates/blob/master/src/Date/CalendarEdit.tsx#L142

**Comment by andy-io** [comment]
i found a fix after some googling that the jsc flavour must be changed

So here is the fix 
there is jscFlavor variable in the app/build.gradle, change that to the following from:

def jscFlavor = 'org.webkit:android-jsc:+'

to:

def jscFlavor = 'org.webkit:android-jsc-intl:+'

This way Intl will be included in the JSC.

So i am closing the issue.

**Comment by RichardLindhout** [comment]
👍 

If you ever want to enable hermes follow the Android caveats section
https://github.com/web-ridge/react-native-paper-dates#android-caveats

**Comment by mikib0** [comment]
@andy-io pls how can i solve this issue in expo?

**Comment by mikib0** [comment]
I am using expo and got the same problem. I solved it by installing the intl polyfill  `pnpm add intl` and importing it in my project like so: 
`import 'intl';
import 'intl/locale-data/jsonp/en'; `
[stackoverflow: Using Intl properly in Android React Native app](https://stackoverflow.com/questions/56943813/using-intl-properly-in-android-react-native-app/65581430#65581430)

**Comment by RichardLindhout** [comment]
You should not do that, just enable hermes and you won't need any polyfills.
Polyfills are bad since they add a lot size to your app size

https://docs.expo.dev/guides/using-hermes/
