### ISSUE TITLE
Does the calendar supports the dot indicators

### ISSUE THREAD

**Issue by kaisiant** [web-ridge/react-native-paper-dates#58]
For example 
![image](https://user-images.githubusercontent.com/26655111/111583623-b186b780-87f7-11eb-9966-018b2ae661e2.png)
(from react-native-calendars)

**Comment by RichardLindhout** [comment]
Maybe we should add it but it's not in the Material Design Specification (yet)

**Comment by RichardLindhout** [comment]
to answer your question: we do not support this at the moment.

**Comment by RichardLindhout** [comment]
@kaisiant I need this feature now in one of my apps so maybe this will get added after all
