### ISSUE TITLE
Mobile calendar pickers adapt to a device’s orientation.

### ISSUE THREAD

**Issue by RichardLindhout** [web-ridge/react-native-paper-dates#6]
![unnamed](https://user-images.githubusercontent.com/6492229/90679050-e6319100-e25f-11ea-8959-da99d2149d58.png)

**Comment by SimonAM** [comment]
For future reference: this library does not currently support landscape view. The top bar is too high and the calendar does not allow vertical scrolling.

**Comment by vinayn-mend** [comment]
> For future reference: this library does not currently support landscape view. The top bar is too high and the calendar does not allow vertical scrolling.

Is there any workaround to support landscape mode on mobile phones?
