### ISSUE TITLE
Is there a way to override the automatic title text color?

### ISSUE THREAD

**Issue by lemmatos** [web-ridge/react-native-paper-dates#60]
If not, it would be nice to have a dark=`boolean` prop, like on the Appbar, to override the automatic title color based on the background.
I'm in need of such a feature, or a way to set the color to whatever I'd like, without changing the background color.

From [Appbar docs](https://callstack.github.io/react-native-paper/appbar.html):

> **dark**
> Type: `boolean`
> Whether the background color is a dark color. A dark appbar will render light text and vice-versa.

**Comment by prankymat** [comment]
agree, we're trying to use #000000 as Primary color which makes the text color very dark as well and not able to see which field is editing.

![image](https://user-images.githubusercontent.com/2998111/111795961-a7051480-8902-11eb-83ee-170822a364ef.png)

**Comment by RichardLindhout** [comment]
@prankymat your issue should not be happening and we should use this hook there instead of color: #000
https://github.com/web-ridge/react-native-paper-dates/blob/master/src/utils.ts#L34
