### ISSUE TITLE
Datepicker picks the day before

### ISSUE THREAD

**Issue by laquesisa** [web-ridge/react-native-paper-dates#61]
I've got the following issue that when I choose a date on the Single date picker that it returns me the day before.

Example:
- I choose: 2th March 2021
- Logging what the date picker returns: console.log(params.date) => 2021-03-01T23:00:00.000Z

I've set the default timezone as described in the Readme, but this happens on IOS and Android.

**Comment by laquesisa** [comment]
Issue on my side :)

**Comment by melihmuratpesmen** [comment]
> Issue on my side :)



> I've got the following issue that when I choose a date on the Single date picker that it returns me the day before.
> 
> Example:
> 
>     * I choose: 2th March 2021
> 
>     * Logging what the date picker returns: console.log(params.date) => 2021-03-01T23:00:00.000Z
> 
> 
> I've set the default timezone as described in the Readme, but this happens on IOS and Android.

Hi @laquesisa I got same problem. How can i fix it or what is causing this?

**Comment by RichardLindhout** [comment]
Please update the package it was a bug in previous versions.
Also make sure you have set the timezone in in formatjs + make sure you have followed the expo/react-native thing
