### ISSUE TITLE
Jumpy modal on notch devices

### ISSUE THREAD

**Issue by kations** [web-ridge/react-native-paper-dates#62]
Hi, 
on notch devices the safe area is jumping on initial render.

Have a look at: 
https://user-images.githubusercontent.com/6721322/111995957-d5a90800-8b19-11eb-91a0-a1cd1e5e3379.mov

would be great to calculate padding top upfront. Great work so far 👍🏻

**Comment by RichardLindhout** [comment]
Strange, React Native default handling of the safe area sucks I'll try to see if I can fix this but short on time a.t.m. PR is welcome!

**Comment by RichardLindhout** [comment]
Looks like it only happening with the range picker and somehow the height is changing while the modal opens. I suspect the SafeAreaView. But on the other hand no problems with the single picker so it's a strange problem

**Comment by RichardLindhout** [comment]
This is fixed with safe-area-context in new version :)
