### ISSUE TITLE
Invalid attempt to destructure non-iterable instance.

### ISSUE THREAD

**Issue by ApetweBc** [web-ridge/react-native-paper-dates#65]
I am trying the picker on the expo app, I get this error. I tried the sample Single Date picker code. why is the destructing array but it expects an object. 

```
Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```
  ```
const [date, setDate] = (React.useState < Date) | (undefined > undefined);
  const [open, setOpen] = React.useState(false);
```

Changing it to this solves the problem but throws an errow ```setOpen is not a fucntion``` when I dismissed the modal
```
const {date, setDate} = (React.useState < Date) | (undefined > undefined);
  const {open, setOpen} = React.useState(false);
```

**Comment by RichardLindhout** [comment]
```tsx
const [date, setDate] = React.useState<Date | undefined>(undefined)
```

I think you're pasting typescript code in your javascript code. Javascript version looks like

```jsx
const [date, setDate] = React.useState(undefined)
```

**Comment by conor909** [comment]
You can add the tsconfig options from the [typescript docs](https://storybook.js.org/docs/react/configure/typescript)

But I cannot get this working for the web, I'm interested if you tested it on web @ApetweBc ?

**Comment by RichardLindhout** [comment]
@conor909 Maybe update react-native-web, maybe your have an older version where the modal was not added yet.

**Comment by conor909** [comment]
Yes, the issue has been referenced here #37, it’s because I initialized by project with expo.

**Comment by Kadweka** [comment]
change it from     const [userInfo] = useContext(AuthContext) to     const {userInfo}= useContext(AuthContext)

**Comment by Faiaz-Rahman** [comment]
> change it from const [userInfo] = useContext(AuthContext) to const {userInfo}= useContext(AuthContext)

It worked just fine. Thanks a lot! Kadweka!
