### ISSUE TITLE
Accepting invalid DATE, YEAR while in text mode and returning last selected date.

### ISSUE THREAD

**Issue by SantoshVarunk** [web-ridge/react-native-paper-dates#66]
https://user-images.githubusercontent.com/43469683/113103777-57391e00-921d-11eb-8462-ac2380a7794d.mov

https://user-images.githubusercontent.com/43469683/113103812-60c28600-921d-11eb-9ea5-62d72bc41690.mov

**Comment by RichardLindhout** [comment]
Expected behaviour, but we could set the text field to red to indicate something is wrong
