### ISSUE TITLE
A require cycle warning raised when debug with Android emulator

### ISSUE THREAD

**Issue by heyouxian** [web-ridge/react-native-paper-dates#72]
Error description:
Require cycle: node_modules\react-native-paper-dates\src\Time\AnalogClock.tsx -> node_modules\react-native-paper-dates\src\Time\AnalogClockHours.tsx -> node_modules\react-native-paper-dates\src\Time\AnalogClock.tsx

I used latest 0.4.5 version and checked source code, the issue really exists in typescript source files.

**Comment by RichardLindhout** [comment]
This is not an error but a warning right?

**Comment by hariks789** [comment]
This is caused by the 
`export const circleSize = 215` in AnalogClock.tsx file
Moving the export to timeUtils.ts will fix this

**Comment by hariks789** [comment]
#74
