### ISSUE TITLE
TypeError: _i.call is not a function

### ISSUE THREAD

**Issue by onlineworld69** [web-ridge/react-native-paper-dates#76]
Hello there. I got an issue while trying to add this code of line into my project. Please advise!
  const [date, setDate] = (React.useState < Date) | (undefined > undefined);

![Screen Shot 2021-05-03 at 15 00 26](https://user-images.githubusercontent.com/13715145/116853488-56cae300-ac20-11eb-92fb-b864218960a5.png)
![Screen Shot 2021-05-03 at 15 00 22](https://user-images.githubusercontent.com/13715145/116853481-53cff280-ac20-11eb-8f44-50e5502980b1.png)

**Comment by RichardLindhout** [comment]
You're using typescript in a javascript project
See https://github.com/web-ridge/react-native-paper-dates/issues/65

**Comment by RichardLindhout** [comment]
Should be
```const [date, setDate] = React.useState(undefined)```

**Comment by onlineworld69** [comment]
Thank you for your timely response Richard.It worked. I am still a newbie :)

**Comment by RichardLindhout** [comment]
No problem, it should be better documented, thanks for the issue report so users in the future can search on the same error!
