### ISSUE TITLE
Allow validRange for Time Picker

### ISSUE THREAD

**Issue by jonnyasmar** [web-ridge/react-native-paper-dates#78]
Subject really says it all. There doesn't seem to be a way to define a `validRange` for the Time Picker.

**Comment by jonnyasmar** [comment]
Sorry, I should've elaborated on that to begin with.

My specific use-case is that I'm creating a form with a "deadline" field. That deadline has to be some point in the future. While I could, of course, employ validations to check this, I would prefer to be able to restrict the time picker from being able to select a time in the past if the date picker is set to "today".

I could also imagine other scenarios such as a time picker that must be within "business hours".

**Comment by justinyum98** [comment]
@RichardLindhout , just wanted to comment that I would love this feature too!

My use-case is setting an appointment. Obviously, it should be impossible to set an appointment in the past.
For now, I am using errors messages to communicate to the user that the start and end times cannot be set in the past.
However, it would be awesome to simply restrict the user to a certain time frame, giving them less options to choose from.

**Comment by RichardLindhout** [comment]
PR for this appreciated!

**Comment by jonnyasmar** [comment]
Sorry! I've been swamped with a new job, new home, and new baby. I most likely won't have time to contribute to this until at least Q1'22.

I'd be happy to help review/test in the meantime if someone else can contribute before then.

**Comment by luzpm1102** [comment]
Hi, I also was looking for doing something like that (I mean, place only business hours 8-12pm, 1-5pm) but I can't find the way of implementing this.
