### ISSUE TITLE
How to disable/remove the year picker within the modal

### ISSUE THREAD

**Issue by ricohumme** [web-ridge/react-native-paper-dates#80]
Hi,

I'm trying to remove the year picker in the modal but so far I'm not finding a solution for this.
The year picker shows the years from 1800 to 2200. 
I've tried limiting these results all together by adding the `validRange` property, but this only seems to work on the calendar and does not limit the years in the picker.

How would I get this done?

Thanks in advance !

**Comment by RichardLindhout** [comment]
Not possible a.t.m. but looks like a good enhancement. Is there something written on this in the Material Design Spec

**Comment by ricohumme** [comment]
Wouldn't know where to look for this on material.io/design. under which section should this be?

**Comment by francesco-clementi-92** [comment]
I'd like also the possibility to select only month and year.

It's a common use case to select just the month and the year.

**Comment by RichardLindhout** [comment]
@francesco-clementi-92 please create a different issue for that, I'll add it to the enhancement list then.
