### ISSUE TITLE
How do I get an Onchange value from TimePicker?

### ISSUE THREAD

**Issue by Guilhermepepe** [web-ridge/react-native-paper-dates#81]
I'm trying to collect the value of the selected time in order to be able to use it in databases, but I can't even display it, how do I do it?

**Comment by RichardLindhout** [comment]
What is your code + what format do you need it ?

You can use the onConfirm callback of the time picker

**Comment by Guilhermepepe** [comment]
Estou utilizando o mesmo código do exemplo dado na sua documentação.
Porém preciso saber como pegar o valor de hours e minutes e inseri-los ao meu banco de dados pela API.
Estou tentando usar onConfirm para atribuir este valor, mas não sei se estou utilizando de maneira correta

`[response.nome_medico[0].nome_medico, value, valueEspec, date, `${onConfirm}` + ":00"]`   //este é o codigo usado para tentar chamar o valor dentro da api

**Comment by Guilhermepepe** [comment]
I am using the same code as the example given in your documents.
However, I need to know how to get the hour and minute value and insert it into my database using the API.
I'm trying to use onConfirm to assign this value, but I don't know if I'm using it correctly

[response.medical_name [0] .medical_name, value, valueEspec, date, $ {onConfirm} + ": 00"]     // this is the code used to try to call the value within the api

**Comment by Guilhermepepe** [comment]
I am using the same code as the example given in your documents.
However, I need to know how to get the hour and minute value and insert it into my database using the API.
I'm trying to use onConfirm to assign this value, but I don't know if I'm using it correctly

`[response.medical_name [0] .medical_name, value, valueEspec, date, $ {onConfirm} + ": 00"]` // this is the code used to try to call the value within the api

**Comment by RichardLindhout** [comment]
https://github.com/web-ridge/react-native-paper-dates/blob/master/example/src/AppInner.tsx#L347
https://github.com/web-ridge/react-native-paper-dates/blob/master/example/src/AppInner.tsx#L105

You get this as an object back in the callback you should do the api call within your callback
