### ISSUE TITLE
App crashes when opening Datepicker in release mode.

### ISSUE THREAD

**Issue by ParthShrivastav** [web-ridge/react-native-paper-dates#82]
Date picker is working totally fine when I am developing the application, but as I try the app after creating the debug apk or release apk on android, it causes the app crash.

**Comment by RichardLindhout** [comment]
Did you have Chrome debugging enabled in your test app, because it uses another engine then if I'm correct with maybe great Intl support.

Which platform does the app crash and do you use hermes and which platforms?

**Comment by RichardLindhout** [comment]
Can't reproduce
