### ISSUE TITLE
I'd like also the possibility to select only month and year.

### ISSUE THREAD

**Issue by Erns** [web-ridge/react-native-paper-dates#84]
I'd like also the possibility to select only month and year.

It's a common use case to select just the month and the year.

_Originally posted by @francesco-clementi-92 in https://github.com/web-ridge/react-native-paper-dates/issues/80#issuecomment-869005131_

**Comment by RichardLindhout** [comment]
I don't have this use-case myself so I won't built it myself. There's als not written something about this picker in the Material Design specification, maybe we can lookup some example of a Google app who does this and screenshot te layout for inspiration if there is a good looking someone can pick it up to create a PR but I think we first need to decide on a layout.

**Comment by francesco-clementi-92** [comment]
Hi @RichardLindhout, I think we can refer to this guidelines:
[https://material-ui-pickers.dev/demo/datepicker#different-views](https://material-ui-pickers.dev/demo/datepicker#different-views).

The site is a little bit outdated, but even the new version https://next.material-ui.com/components/date-picker/ is pretty much the same (can't find an example)

**Comment by RichardLindhout** [comment]
Looking good! I'll accept a PR which adds this component
- Uses Intl for the month names
- Uses FlatList for year
- Uses Flatlist for month grid

**Comment by nguyenhoa072** [comment]
How to use this feature?
thanks you so much.
