### ISSUE TITLE
With Date Range,  lighter color not applied on days between the range

### ISSUE THREAD

**Issue by mashaalmemon** [web-ridge/react-native-paper-dates#85]
We're using react-native-paper in our project and have a custom theme.

We're finding that:
* When we use our custom primary color in the theme, when selecting date ranges the lighter color does not show up between the date range - only the start/end date have a circle with the primary color selected, and everything in between is the same color as the rest of the calendar.
* When we comment out our primary color in the theme, the date picker works exactly as it should, using the default purple primary color for the dates selected, and having the lighter purple for the dates in between start/end dates selected.

Is there another color we have to specify in the react-native-paper theme to get this working right?

**Comment by colinmatthewlee** [comment]
I've been experiencing this issue too, specifically when I set the primary color in theme to "#5F53FC", a lighter color connecting the two dates does not show up for me.

**Comment by mashaalmemon** [comment]
@chakrihacker @RichardLindhout @nandorojo Any guidance you can give us on this would be fantastic.

**Comment by chakrihacker** [comment]
Can you share a code snippet that I can try locally

**Comment by iM-GeeKy** [comment]
I only tested this on the iPhone simulator, it should at least demonstrate the issue at hand. (https://snack.expo.dev/2IrVHMYvU)

**Comment by mashaalmemon** [comment]
@iM-GeeKy thanks for taking the time to setup the snack example and demonstrate the issue we're facing here. Much appreciated. 

@chakrihacker, if you look at @iM-GeeKy 's example project, when selecting a range there is no light-blue highlight between the date ranges; you'll notice he specified a primary color in the react-native-paper theme. But as soon as you delete that custom primary color, the light purple highlight works!

**Comment by chakrihacker** [comment]
@mashaalmemon and @iM-GeeKy test my branch and verify if it's working or not?

**Comment by iM-GeeKy** [comment]
@chakrihacker I tried your branch and it didn't seem to resolve the issue. As a sanity check, are you (@mashaalmemon) seeing the same behavior?

**Comment by RichardLindhout** [comment]
I already merged it but haven't tested it yet, if somebody has a fix I'll merge it into main

**Comment by chakrihacker** [comment]
> @iM-GeeKy thanks for taking the time to setup the snack example and demonstrate the issue we're facing here. Much appreciated.
> 
> @chakrihacker, if you look at @iM-GeeKy 's example project, when selecting a range there is no light-blue highlight between the date ranges; you'll notice he specified a primary color in the react-native-paper theme. But as soon as you delete that custom primary color, the light purple highlight works!

How did you test my branch?

**Comment by iM-GeeKy** [comment]
In one of my private repositories I pointed to your branch in my package.json, deleted my node_modules, and did a fresh install. I will add that I think the fix did help to a degree, but for lighter colors (ie. #2979FF, #5F53FC) the highlight is so faint it appears almost white. Thanks for the quick response times! Perhaps the ratio in your changes needs to be tweaked to accommodate for lighter hues.

**Comment by chakrihacker** [comment]
I think we can introduce a prop for the user to set the ratio of color lightness, right now it's 90% lightness of the primary color, so It depends on the primary color. Having hardcoded values might not be the best way. What are your thoughts @RichardLindhout ?

**Comment by RichardLindhout** [comment]
checking if it's light or dark I think there is something in the color for that or in the react-native-paper codebase already

**Comment by RichardLindhout** [comment]
I don't know if anything is written on it in the spec

**Comment by crussell122** [comment]
I just submitted a pr for the new rangeOpacity prop that I added in my branch. Please let me know if it works for you all.

**Comment by chakrihacker** [comment]
What do you think of this approach of tint color @RichardLindhout ?

https://codesandbox.io/s/friendly-brattain-s1n7z?file=/src/App.js

**Comment by RichardLindhout** [comment]
I think it's good but it has to take in account the following things
Dark theme RNN
Primary color
etc

**Comment by iM-GeeKy** [comment]
> I think it's good but it has to take in account the following things Dark theme RNN Primary color etc

Is that not what @chakrihacker is mocking with his demo above? Where "Tinted Color" would correspond to dark theme color and so on...

**Comment by SharfMohiuddin** [comment]
Any solution? I'm facing the same issue. Selected range color is dark as it should be light and selected dates behind the selected range is hiding.
```
 const customDarkTheme = {
    ...DarkTheme,
    roundness: 2,
    colors: {
      ...DarkTheme.colors,
      primary: Colors.PRIMARY_GREEN,
      background: Colors.background,
      accent: "#ff1744",
      text: Colors.WHITE,
      surface: Colors.card_bg,
    },
    fonts: {
      regular: {
        fontFamily: typography.font_monsterrat_regular,
      },
    },
  };

  <PaperProvider theme={customDarkTheme}>
        <>
          <DatePickerModal
            saveLabel={
              <Text style={{ color: Colors.PRIMARY_GREEN, fontWeight: "bold" }}>
                Done
              </Text>
            }
            locale="en"
            mode="range"
            visible={open}
            onDismiss={onDismiss}
            startDate={range.startDate}
            endDate={range.endDate ? range.endDate : range.startDate} // Set the end date to the start date by default
            onConfirm={handleDateRangeSelect}
            validRange={{
              startDate: new Date(2021, 1, 2), // optional
              endDate: new Date(), // optional
            }}
            editIcon={false}
            label="Select Date"
            animationType="fade"
            startLabel=""
            endLabel=""
          />
        </>
      </PaperProvider>
```

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-31 at 11 19 43](https://github.com/web-ridge/react-native-paper-dates/assets/111132563/92f0f35f-8917-4b73-9127-1cd976a2117b)

**Comment by iM-GeeKy** [comment]
@SharfMohiuddin PR's are welcome! As a temporary fix you can always create a patch using `patch-package`.

**Comment by jhsu98** [comment]
I'm running into this same issue. When I override the theme.colors.primary default value I'm missing the tinted background for the dates between start and end. Has anybody found a reliable solution?
