### ISSUE TITLE
TimePickerModal uses different time formats for locale="fr-CA" between Android and iOS

### ISSUE THREAD

**Issue by colinmatthewlee** [web-ridge/react-native-paper-dates#86]
For TimePickerModal, I am expecting a 24-hour-clock format using locale="fr-CA".

I get the 24-hour format for iOS simulators, but for android emulators I am stuck with the am/pm format.

There was a similar issue in #24 , which was closed but didn't seem to fix the issue for me.

**iOS simulator**
![Screen Shot 2021-07-20 at 5 55 22 PM](https://user-images.githubusercontent.com/54291931/126400895-507a3729-85a3-47ab-8299-d0dddace535c.png)

**Android emulator**
![Screen Shot 2021-07-20 at 5 54 30 PM](https://user-images.githubusercontent.com/54291931/126400942-ce161de3-db85-45b9-9554-0d996879682f.png)

I am using "react-native-paper-dates": "^0.4.6", and   "react-native": "^0.63.4"

**Comment by RichardLindhout** [comment]
Should not happen:

Have you followed the android-caveats section? https://github.com/web-ridge/react-native-paper-dates#android-caveats

**Comment by colinmatthewlee** [comment]
Fixed, thank you. I added the code into my index file but didn't add a "fr" version
