### ISSUE TITLE
The date isn't updated if user types at the middle.

### ISSUE THREAD

**Issue by funnywebdev** [web-ridge/react-native-paper-dates#98]
![5](https://user-images.githubusercontent.com/19596995/131562232-d85ba4ac-0399-4f9a-92ba-efc78966d3b1.png)
If the user types at the middle of the input in this screen, the date isn't updated.
Line 79-81 of `TextInputMask.tsx` file should be fixed like this if you don't mind.

```
    if (enhancedText.length === mask.length) {
      onChangeText && onChangeText(enhancedText)
    }
```

**Comment by iM-GeeKy** [comment]
Closed by https://github.com/web-ridge/react-native-paper-dates/pull/207
