### ISSUE TITLE
App crashes when opening Datepicker in production mode when running on Android Device on Expo

### ISSUE THREAD

**Issue by mogarick** [web-ridge/react-native-paper-dates#99]
Just as stated in #82 , everything works fine on dev mode in expo but if I execute prod mode:

```
> expo start -c --no-dev
```
The app crashes as soon as I try to open the Date picker.

I'm not using Hermes but I followed the "Android caveats" instructions anyway, including: 

* the installation of polyfills.
```
> npm install react-native-localize @formatjs/intl-pluralrules @formatjs/intl-getcanonicallocales @formatjs/intl-listformat @formatjs/intl-displaynames @formatjs/intl-locale @formatjs/intl-datetimeformat @formatjs/intl-numberformat @formatjs/intl-relativetimeformat --save

```

* adding the polyfill code on App.android.tsx:

``` ts

require("@formatjs/intl-getcanonicallocales/polyfill");
require("@formatjs/intl-locale/polyfill");

require("@formatjs/intl-pluralrules/polyfill");
require("@formatjs/intl-pluralrules/locale-data/es.js"); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

require("@formatjs/intl-displaynames/polyfill");
require("@formatjs/intl-displaynames/locale-data/es.js"); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

require("@formatjs/intl-listformat/polyfill");
require("@formatjs/intl-listformat/locale-data/es.js"); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

require("@formatjs/intl-numberformat/polyfill");
require("@formatjs/intl-numberformat/locale-data/es.js"); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

require("@formatjs/intl-relativetimeformat/polyfill");
require("@formatjs/intl-relativetimeformat/locale-data/es.js"); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

require("@formatjs/intl-datetimeformat/polyfill");
require("@formatjs/intl-datetimeformat/locale-data/es.js"); // USE YOUR OWN LANGUAGE OR MULTIPLE IMPORTS YOU WANT TO SUPPORT

require("@formatjs/intl-datetimeformat/add-golden-tz.js");

// https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone

if ("__setDefaultTimeZone" in Intl.DateTimeFormat) {
  // If you are using react-native-cli
  // let RNLocalize = require('react-native-localize');
  // Intl.DateTimeFormat.__setDefaultTimeZone(RNLocalize.getTimeZone());

  //  Are you using Expo, use this instead of previous 2 lines
  //@ts-ignore
  Intl.DateTimeFormat.__setDefaultTimeZone(
    require("expo-localization").timezone
  );
}
```

The android Device is a Redmi Note 8, running Android 10 QKQ1.200114.002

## Additional notes
The problem doesn't occur on iOS. But it renders the picker with the default colors not respecting the custom ones used in the rest of the app via RNPaper theme (it does use my custom them on dev mode)

In web it works fine and it does respect my custom theme colors.

**Comment by mogarick** [comment]
The problem is indeed solved using the polyfill. I had a typo. The file was named `App. android.tsx` and it should be `App.android.tsx`. Fixing this made the picker work but with the same weird behavior of iOS by not respecting the RNPaper customization.

The other thing to relevant to notice is that I'm not using Hermes but even the polyfill is needed regardless. 
If I add the conditional to include the polyfill only if `isHermesEnabled` the app crashes. 
I don't know from which version of android the polyfill is not needed but version 10 needs it.

@RichardLindhout should I close this issue and create a new one for the theming problem with android and iOS?

**Comment by RichardLindhout** [comment]
Yes please do + I changed the readme to me more clear the android and hermes checks are not needed
